import {
    DEBIT_CARD_INQUIRY_LOADING,
    DEBIT_CARD_INQUIRY_SUCCESS,
    DEBIT_CARD_INQUIRY_ERROR,
    DEBIT_CARD_INQUIRY_CLEAR,
} from "@redux/actions/services/debitCardInquiryAction";

const initialState = {
    status: "idle",
    error: null,
    data: null,
    msgBody: null,
    msgHeader: null,
    dateTime: null,
    debitCardNumber: null,
    debtCardNxtAct: null,
    debtCardSt: null,
    expYr: null,
    msgTypeId: null,
    ovrSeasFlg: null,
    ovrSeasFlgEndDt: null,
    ovrSeasFlgStDt: null,
    primBitmap: null,
    resrvFld: null,
    sysAuditTrailNo: null,
    termId: null,
    dest: null,
    envRegion: null,
    hostStatusCode: null,
    hostStatusDesc: null,
    loginId: null,
    pAN: null,
    paginationKey: null,
    patType: null,
    recLength: null,
    recNo: null,
    source: null,
    sourceID: null,
    statusCode: null,
    statusDesc: null,
    svcName: null,
    sysStat: null,
    txnCode: null,
    txnDt: null,
    txnTime: null,
    txnType: null,
    debitCardName: "Debit Card",
};

function debitCardInquiryReducer(state = initialState, action) {
    switch (action.type) {
        case DEBIT_CARD_INQUIRY_LOADING:
            return {
                ...state,
                status: "loading",
            };

        case DEBIT_CARD_INQUIRY_ERROR:
            return {
                ...state,
                status: "error",
                error: action.error,
            };

        case DEBIT_CARD_INQUIRY_SUCCESS:
            return {
                ...state,
                data: action.data,
                msgBody: action.msgBody,
                msgHeader: action.msgHeader,
                dateTime: action.dateTime,
                debitCardNumber: action.debitCardNumber,
                debtCardNxtAct: action.debtCardNxtAct,
                debtCardSt: action.debtCardSt,
                expYr: action.expYr,
                msgTypeId: action.msgTypeId,
                ovrSeasFlg: action.ovrSeasFlg,
                ovrSeasFlgEndDt: action.ovrSeasFlgEndDt,
                ovrSeasFlgStDt: action.ovrSeasFlgStDt,
                primBitmap: action.primBitmap,
                resrvFld: action.resrvFld,
                sysAuditTrailNo: action.sysAuditTrailNo,
                termId: action.termId,
                dest: action.dest,
                envRegion: action.envRegion,
                hostStatusCode: action.hostStatusCode,
                hostStatusDesc: action.hostStatusDesc,
                loginId: action.loginId,
                pAN: action.pAN,
                paginationKey: action.paginationKey,
                patType: action.patType,
                recLength: action.recLength,
                recNo: action.recNo,
                source: action.source,
                sourceID: action.sourceID,
                statusCode: action.statusCode,
                statusDesc: action.statusDesc,
                svcName: action.svcName,
                sysStat: action.sysStat,
                txnCode: action.txnCode,
                txnDt: action.txnDt,
                txnTime: action.txnTime,
                txnType: action.txnType,
                debitCardName: action.debitCardName,
            };

        case DEBIT_CARD_INQUIRY_CLEAR:
            return {
                ...state,
                status: "idle",
                error: null,
                data: null,
                msgBody: null,
                msgHeader: null,
                dateTime: null,
                debitCardNumber: null,
                debtCardNxtAct: null,
                debtCardSt: null,
                expYr: null,
                msgTypeId: null,
                ovrSeasFlg: null,
                ovrSeasFlgEndDt: null,
                ovrSeasFlgStDt: null,
                primBitmap: null,
                resrvFld: null,
                sysAuditTrailNo: null,
                termId: null,
                dest: null,
                envRegion: null,
                hostStatusCode: null,
                hostStatusDesc: null,
                loginId: null,
                pAN: null,
                paginationKey: null,
                patType: null,
                recLength: null,
                recNo: null,
                source: null,
                sourceID: null,
                statusCode: null,
                statusDesc: null,
                svcName: null,
                sysStat: null,
                txnCode: null,
                txnDt: null,
                txnTime: null,
                txnType: null,
                debitCardName: "Debit Card",
            };

        default:
            return state;
    }
}
export default debitCardInquiryReducer;
