// DebitCard Inquiry action

export const DEBIT_CARD_INQUIRY_LOADING = () => ({});
export const DEBIT_CARD_INQUIRY_SUCCESS = (
    data,
    msgBody,
    msgHeader,
    dateTime,
    debitCardNumber,
    debtCardNxtAct,
    debtCardSt,
    expYr,
    msgTypeId,
    ovrSeasFlg,
    ovrSeasFlgEndDt,
    ovrSeasFlgStDt,
    primBitmap,
    resrvFld,
    sysAuditTrailNo,
    termId,
    dest,
    envRegion,
    hostStatusCode,
    hostStatusDesc,
    loginId,
    pAN,
    paginationKey,
    patType,
    recLength,
    recNo,
    source,
    sourceID,
    statusCode,
    statusDesc,
    svcName,
    sysStat,
    txnCode,
    txnDt,
    txnTime,
    txnType,
    debitCardName
) => ({
    data: data,
    msgBody: msgBody,
    msgHeader: msgHeader,
    dateTime: dateTime,
    debitCardNumber: debitCardNumber,
    debtCardNxtAct: debtCardNxtAct,
    debtCardSt: debtCardSt,
    expYr: expYr,
    msgTypeId: msgTypeId,
    ovrSeasFlg: ovrSeasFlg,
    ovrSeasFlgEndDt: ovrSeasFlgEndDt,
    ovrSeasFlgStDt: ovrSeasFlgStDt,
    primBitmap: primBitmap,
    resrvFld: resrvFld,
    sysAuditTrailNo: sysAuditTrailNo,
    termId: termId,
    dest: dest,
    envRegion: envRegion,
    hostStatusCode: hostStatusCode,
    hostStatusDesc: hostStatusDesc,
    loginId: loginId,
    pAN: pAN,
    paginationKey: paginationKey,
    patType: patType,
    recLength: recLength,
    recNo: recNo,
    source: source,
    sourceID: sourceID,
    statusCode: statusCode,
    statusDesc: statusDesc,
    svcName: svcName,
    sysStat: sysStat,
    txnCode: txnCode,
    txnDt: txnDt,
    txnTime: txnTime,
    txnType: txnType,
    debitCardName: debitCardName,
});
export const DEBIT_CARD_INQUIRY_ERROR = (error) => ({ error: error });
export const DEBIT_CARD_INQUIRY_CLEAR = () => ({});

export const DEBIT_CARD_LAST_DIGITS = (debitCardLast8Digits) => ({ debitCardLast8Digits });
