export const DRAFT_USER_ACCOUNT_INQUIRY_LOADING = () => ({});

export const DRAFT_USER_ACCOUNT_INQUIRY_ERROR = (error) => ({
    error: error,
});

export const DRAFT_USER_ACCOUNT_INQUIRY_SUCCESS = (
    data,
    accessNo,
    addr1,
    addr2,
    addr3,
    addr4,
    birthDate,
    bodInd,
    branchApprovalStatusCode,
    city,
    customerName,
    customerRiskRating,
    custStatus,
    deChequeHostStatus,
    ekycDone,
    emailAddress,
    employerName,
    empType,
    empTypeValue,
    finanicalObjective,
    gcif,
    gender,
    idNo,
    idType,
    isZestI,
    localCifNo,
    m2uAccessNo,
    m2uIndicator,
    maeInd,
    mobileNo,
    monthlyIncomeRange,
    monthlyIncomeRangeValue,
    nationality,
    occupation,
    occupationValue,
    onboardingIndicatorCode,
    onBoardingStatusInfo,
    onlineRegUrl,
    pep,
    postCode,
    preferredBranch,
    preferredBRDistrict,
    preferredBRState,
    purpose,
    purposeValue,
    race,
    resumeStageInd,
    rsaIndicator,
    saDailyInd,
    saFormInvestmentExp,
    saFormInvestmentNature,
    saFormInvestmentRisk,
    saFormInvestmentTerm,
    saFormPIDM,
    saFormProductFeature,
    saFormSecurities,
    saFormSuitability,
    saTermInd,
    scorePartyResult,
    screeningStatus,
    sector,
    sectorValue,
    sourceOfFund,
    sourceOfFundValue,
    staffInd,
    state,
    stateValue,
    statusCode,
    statusDesc,
    title,
    universalCifNo,
    viewPartyResult,
    screeningId,
    hasDebitCard,
    numOfWatchlistHits
) => ({
    data: data,
    accessNo: accessNo,
    addr1: addr1,
    addr2: addr2,
    addr3: addr3,
    addr4: addr4,
    birthDate: birthDate,
    bodInd: bodInd,
    branchApprovalStatusCode: branchApprovalStatusCode,
    city: city,
    customerName: customerName,
    customerRiskRating: customerRiskRating,
    custStatus: custStatus,
    deChequeHostStatus: deChequeHostStatus,
    ekycDone: ekycDone,
    emailAddress: emailAddress,
    employerName: employerName,
    empType: empType,
    empTypeValue: empTypeValue,
    finanicalObjective: finanicalObjective,
    gcif: gcif,
    gender: gender,
    idNo: idNo,
    idType: idType,
    isZestI: isZestI,
    localCifNo: localCifNo,
    m2uAccessNo: m2uAccessNo,
    m2uIndicator: m2uIndicator,
    maeInd: maeInd,
    mobileNo: mobileNo,
    monthlyIncomeRange: monthlyIncomeRange,
    monthlyIncomeRangeValue: monthlyIncomeRangeValue,
    nationality: nationality,
    occupation: occupation,
    occupationValue: occupationValue,
    onboardingIndicatorCode: onboardingIndicatorCode,
    onBoardingStatusInfo: onBoardingStatusInfo,
    onlineRegUrl: onlineRegUrl,
    pep: pep,
    postCode: postCode,
    preferredBranch: preferredBranch,
    preferredBRDistrict: preferredBRDistrict,
    preferredBRState: preferredBRState,
    purpose: purpose,
    purposeValue: purposeValue,
    race: race,
    resumeStageInd: resumeStageInd,
    rsaIndicator: rsaIndicator,
    saDailyInd: saDailyInd,
    saFormInvestmentExp: saFormInvestmentExp,
    saFormInvestmentNature: saFormInvestmentNature,
    saFormInvestmentRisk: saFormInvestmentRisk,
    saFormInvestmentTerm: saFormInvestmentTerm,
    saFormPIDM: saFormPIDM,
    saFormProductFeature: saFormProductFeature,
    saFormSecurities: saFormSecurities,
    saFormSuitability: saFormSuitability,
    saTermInd: saTermInd,
    scorePartyResult: scorePartyResult,
    screeningStatus: screeningStatus,
    sector: sector,
    sectorValue: sectorValue,
    sourceOfFund: sourceOfFund,
    sourceOfFundValue: sourceOfFundValue,
    staffInd: staffInd,
    state: state,
    stateValue: stateValue,
    statusCode: statusCode,
    statusDesc: statusDesc,
    title: title,
    universalCifNo: universalCifNo,
    viewPartyResult: viewPartyResult,
    screeningId: screeningId,
    hasDebitCard: hasDebitCard,
    numOfWatchlistHits: numOfWatchlistHits,
});

export const DRAFT_USER_ACCOUNT_INQUIRY_UPDATE_ACCOUNT_NUMBER = (acctNo) => ({
    acctNo: acctNo,
});

export const DRAFT_USER_ACCOUNT_INQUIRY_CLEAR = () => ({});
