export const MASTERDATA_LOADING = () => ({});

export const MASTERDATA_ERROR = (error) => ({
    error: error,
});

export const MASTERDATA_SUCCESS = (
    data,
    branchStateData,
    countryOfBirth,
    crsStatus,
    employmentType,
    estimatedMonthlyTxnAmount,
    estimatedMonthlyTxnVolume,
    fatcaCountryList,
    fatcaStatus,
    gender,
    icStateCode,
    icTypes,
    incomeRange,
    maeResidentialCountry,
    permanentresidentcountry,
    purpose,
    occupation,
    race,
    residentialcountryforeigner,
    sector,
    sourceOfFundCountry,
    sourceOfFundOrigin,
    sourceOfWealthOrigin,
    stateData,
    title,
    zestActivationAmountNTB,
    m2uPremierActivationAmountNTB,
    zestActivationAmountETB,
    m2uPremierActivationAmountETB,
    maeCitizenship,
    debitCardApplicationAmount,
    casaPageDescriptionValue
) => ({
    data,
    branchStateData,
    countryOfBirth,
    crsStatus,
    employmentType,
    estimatedMonthlyTxnAmount,
    estimatedMonthlyTxnVolume,
    fatcaCountryList,
    fatcaStatus,
    gender,
    icStateCode,
    icTypes,
    incomeRange,
    maeResidentialCountry,
    permanentresidentcountry,
    purpose,
    occupation,
    race,
    residentialcountryforeigner,
    sector,
    sourceOfFundCountry,
    sourceOfFundOrigin,
    sourceOfWealthOrigin,
    stateData,
    title,
    maeCitizenship,
    zestActivationAmountNTB,
    m2uPremierActivationAmountNTB,
    zestActivationAmountETB,
    m2uPremierActivationAmountETB,
    debitCardApplicationAmount,
    casaPageDescriptionValue,
});

export const MASTERDATA_CLEAR = () => ({});

export const MASTERDATA_UPDATE_SOURCE_OF_FUND_COUNTRY = (sourceOfFundCountry) => ({
    sourceOfFundCountry,
});
