export const PREPOSTQUAL_LOADING = () => ({});

export const PREPOSTQUAL_ERROR = (error) => ({
    error: error,
});

export const PREPOSTQUAL_SUCCESS = (
    data,
    custStatus,
    branchApprovalStatusCode,
    m2uIndicator,
    idNo,
    mobileNo,
    addr1,
    addr2,
    addr3,
    addr4,
    idType,
    birthDate,
    customerName,
    postCode,
    m2uAccessNo,
    gcif,
    onlineRegUrl,
    maeInd,
    resumeStageInd,
    rsaIndicator,
    localCifNo,
    universalCifNo,
    customerRiskRating,
    screeningStatus,
    title,
    nationality,
    bodInd,
    staffInd,
    saDailyInd,
    saTermInd,
    deChequeHostStatus,
    onBoardingStatusInfo,
    onboardingIndicatorCode,
    emailAddress,
    pep,
    gender,
    race,
    state,
    city,
    empType,
    empTypeValue,
    employerName,
    occupation,
    sector,
    monthlyIncomeRange,
    purpose,
    preferredBRState,
    preferredBRDistrict,
    preferredBranch,
    finanicalObjective,
    finanicalObjectiveValue,
    saFormSecurities,
    saFormInvestmentRisk,
    saFormInvestmentExp,
    saFormInvestmentNature,
    saFormInvestmentTerm,
    saFormProductFeature,
    saFormPIDM,
    saFormSuitability,
    monthlyIncomeRangeValue,
    occupationValue,
    purposeValue,
    sectorValue,
    sourceOfFund,
    sourceOfFundValue,
    stateValue,
    statusCode,
    statusDesc,
    viewPartyResult,
    txRefNo,
) => ({
    data: data,
    statusCode: statusCode,
    statusDesc: statusDesc,
    custStatus: custStatus,
    branchApprovalStatusCode: branchApprovalStatusCode,
    m2uIndicator: m2uIndicator,
    idNo: idNo,
    mobileNo: mobileNo,
    addr1: addr1,
    addr2: addr2,
    addr3: addr3,
    addr4: addr4,
    idType: idType,
    birthDate: birthDate,
    customerName: customerName,
    postCode: postCode,
    m2uAccessNo: m2uAccessNo,
    gcif: gcif,
    onlineRegUrl: onlineRegUrl,
    maeInd: maeInd,
    resumeStageInd: resumeStageInd,
    rsaIndicator: rsaIndicator,
    localCifNo: localCifNo,
    universalCifNo: universalCifNo,
    customerRiskRating: customerRiskRating,
    screeningStatus: screeningStatus,
    title: title,
    nationality: nationality,
    bodInd: bodInd,
    staffInd: staffInd,
    saDailyInd: saDailyInd,
    saTermInd: saTermInd,
    deChequeHostStatus: deChequeHostStatus,
    onBoardingStatusInfo: onBoardingStatusInfo,
    onboardingIndicatorCode: onboardingIndicatorCode,
    emailAddress: emailAddress,
    pep: pep,
    gender: gender,
    race: race,
    state: state,
    stateValue: stateValue,
    city: city,
    empType: empType,
    empTypeValue: empTypeValue,
    employerName: employerName,
    occupation: occupation,
    occupationValue: occupationValue,
    sector: sector,
    sectorValue: sectorValue,
    monthlyIncomeRange: monthlyIncomeRange,
    monthlyIncomeRangeValue: monthlyIncomeRangeValue,
    purpose: purpose,
    purposeValue: purposeValue,
    preferredBRState: preferredBRState,
    preferredBRDistrict: preferredBRDistrict,
    preferredBranch: preferredBranch,
    finanicalObjective: finanicalObjective,
    finanicalObjectiveValue: finanicalObjectiveValue,
    saFormSecurities: saFormSecurities,
    saFormInvestmentRisk: saFormInvestmentRisk,
    saFormInvestmentExp: saFormInvestmentExp,
    saFormInvestmentNature: saFormInvestmentNature,
    saFormInvestmentTerm: saFormInvestmentTerm,
    saFormProductFeature: saFormProductFeature,
    saFormPIDM: saFormPIDM,
    saFormSuitability: saFormSuitability,
    sourceOfFund: sourceOfFund,
    sourceOfFundValue: sourceOfFundValue,
    viewPartyResult: viewPartyResult,
    txRefNo,
});

export const PREPOSTQUAL_UPDATE_FROM_CREATE_ACCOUNT = (
    accessNo,
    acctCode,
    acctNo,
    acctType,
    assessmentId,
    customerRiskRating,
    customerRiskRatingValue,
    debitCardNo,
    expiryDate,
    inviteCode,
    nameScreenFlag,
    nextReviewDate,
    numOfWatchlistHits,
    primBitMap,
    refNo,
    s2w,
    sanctionsTagging,
    sanctionsTaggingValue,
    screeningId,
    gcif,
    universalCifNo
) => ({
    accessNo: accessNo,
    acctCode: acctCode,
    acctNo: acctNo,
    acctType: acctType,
    assessmentId: assessmentId,
    customerRiskRating: customerRiskRating,
    customerRiskRatingValue: customerRiskRatingValue,
    debitCardNo: debitCardNo,
    expiryDate: expiryDate,
    inviteCode: inviteCode,
    nameScreenFlag: nameScreenFlag,
    nextReviewDate: nextReviewDate,
    numOfWatchlistHits: numOfWatchlistHits,
    primBitMap: primBitMap,
    refNo: refNo,
    s2w: s2w,
    sanctionsTagging: sanctionsTagging,
    sanctionsTaggingValue: sanctionsTaggingValue,
    screeningId: screeningId,
    gcif: gcif,
    universalCifNo: universalCifNo,
});

export const PREPOSTQUAL_FINANICAL_OBJECTIVE = (finanicalObjective, finanicalObjectiveValue) => ({
    finanicalObjective: finanicalObjective,
    finanicalObjectiveValue: finanicalObjectiveValue,
});

export const UPDATE_PRE_QUAL_REDUCER = (
    idType,
    customerEmail,
    customerName,
    mobileNo,
    idNo,
    nationality,
    pdpa,
    addr1,
    addr2,
    addr3,
    custStatus,
    m2uIndicator,
    postCode,
    state,
    stateValue,
    fatcaStateValue,
    empType,
    empTypeValue,
    occupation,
    occupationValue,
    employerName,
    sector,
    sectorValue,
    gender,
    genderValue,
    passportExpiry,
    issuedCountry,
    issuedCountryValue,
    title,
    titleValue,
    race,
    raceValue,
    pep,
    city,
    monthlyIncomeRange,
    monthlyIncomeRangeValue,
    sourceOfIncome,
    sourceOfIncomeValue,
    sourceOfFundCountry,
    sourceOfFundCountryValue,
    riskRating,
    declarePdpaPromotion,
    tc,
    purpose,
    preferredBRDistrict,
    preferredBRState,
    preferredBranch,
    preferredBranchValue,
    saFormInvestmentExp,
    saFormInvestmentNature,
    saFormInvestmentRisk,
    saFormInvestmentTerm,
    saFormPIDM,
    saFormProductFeature,
    saFormSecurities,
    saFormSuitability,
    onBoardingStatusInfo,
    isZestI,
    branchApprovalStatusCode
) => ({
    idType: idType,
    customerEmail: customerEmail,
    customerName: customerName,
    mobileNo: mobileNo,
    idNo: idNo,
    nationality: nationality,
    pdpa: pdpa,
    addr1: addr1,
    addr2: addr2,
    addr3: addr3,
    custStatus: custStatus,
    m2uIndicator: m2uIndicator,
    postCode: postCode,
    state: state,
    stateValue: stateValue,
    fatcaStateValue: fatcaStateValue,
    empType: empType,
    empTypeValue: empTypeValue,
    occupation: occupation,
    occupationValue: occupationValue,
    employerName: employerName,
    sector: sector,
    sectorValue: sectorValue,
    gender: gender,
    genderValue: genderValue,
    passportExpiry: passportExpiry,
    issuedCountry: issuedCountry,
    issuedCountryValue: issuedCountryValue,
    title: title,
    titleValue: titleValue,
    race: race,
    raceValue: raceValue,
    pep: pep,
    city: city,
    monthlyIncomeRange: monthlyIncomeRange,
    monthlyIncomeRangeValue: monthlyIncomeRangeValue,
    sourceOfIncome: sourceOfIncome,
    sourceOfIncomeValue: sourceOfIncomeValue,
    sourceOfFundCountry: sourceOfFundCountry,
    sourceOfFundCountryValue: sourceOfFundCountryValue,
    riskRating: riskRating,
    declarePdpaPromotion: declarePdpaPromotion,
    tc: tc,
    purpose: purpose,
    preferredBRDistrict: preferredBRDistrict,
    preferredBRState: preferredBRState,
    preferredBranch: preferredBranch,
    preferredBranchValue: preferredBranchValue,
    saFormInvestmentExp: saFormInvestmentExp,
    saFormInvestmentNature: saFormInvestmentNature,
    saFormInvestmentRisk: saFormInvestmentRisk,
    saFormInvestmentTerm: saFormInvestmentTerm,
    saFormPIDM: saFormPIDM,
    saFormProductFeature: saFormProductFeature,
    saFormSecurities: saFormSecurities,
    saFormSuitability: saFormSuitability,
    onBoardingStatusInfo: onBoardingStatusInfo,
    isZestI: isZestI,
    branchApprovalStatusCode: branchApprovalStatusCode,
});

export const PREPOSTQUAL_UPDATE_USER_STATUS = (userStatus) => ({
    userStatus: userStatus,
});

export const PREPOSTQUAL_CLEAR = () => ({});
