/* eslint-disable no-unused-vars */
// POST: /fnb/v1/ssl/order/orderDetail

// 3rd party delivery
const Request = {
    orderId: "MBBOR111111111217461",
    isMerchant: true,
};

// Order status - QRMS order status
// Delivery status - Delyva delivery status

export const Response1 = {
    message: "success",
    code: 200,
    challenge: null,
    result: {
        code: 200,
        status: "QR000",
        text: "success",
        recipientName: null,
        products: [
            {
                productId: "MKPRD1000726",
                name: "Chicken and Rice",
                imagePaths: null,
                logo: null,
                priceAmount: null,
                currency: null,
                suitableBike: false,
                sku: null,
                shortDesc: null,
                longDesc: null,
                size: null,
                weight: null,
                categoryName: "Services",
                updateDate: "2021-07-24T16:20:33.043Z",
                deliveryServiceCode: "MBB-SDD-XPRESS",
                outletAddress:
                    "Pantai Panorama condo, 1-15-2, Pantai Dalam, 59200, Kuala Lumpur, Malaysia, kuala lumpur, malaysia",
                merchantContactNo: "0123456789",
                outOfCoverage: "false",
                image: "https://test.vts.maybank.com.my:8553/api/v1/mobile/Images/MBUAT1205414_Picture_.jpeg",
                netAmtWithoutDeliveryAmt: 13.1,
                orderDetailId: 208400,
                totalAmt: "13.10",
                quantity: 1,
                avail: false,
            },
        ],
        addressDetail: {
            addressLine1: null,
            addressLine2: null,
            addressLine3: null,
            city: null,
            state: "WP KUALA LUMPUR",
            postcode: "51000",
            contactNo: "0176491708",
            email: "maquirangdane@gmail.com",
            type: null,
            addressFlag: null,
            deliveryAddress: null,
            address: "A 13 3 the capers Sentul timur Kuala lumpur",
        },
        deliveryType: "3rd Party Delivery",
        categoryId: null,
        merchantId: "MBUAT1205414",
        merchantName: "DaneMerchant003",
        merchantPhNo: null,
        merchantAddress: null,
        promoCode: null,
        totalWeight: null,
        deliveryAmount: 11.66,
        subTotalAmount: null,
        totalPaymentAmount: null,
        orderId: "MBBOR111111111217273",
        customerId: "160000007000310416",
        customerName: "Danielle",
        transactionRefno: "MBUAT111111111436847",
        customerReferenceNo: "172623534Q",
        orderNo: "172623534Q",
        createdDate: "2021-07-21T14:01:39.517Z",
        netAmt: 13.1,
        discountAmt: 0.0,
        finalAmt: 13.1,
        orderStatus: 1,
        deliveryStatus: 1000,
        deliveryId: 1,
        outletAddress:
            "Pantai Panorama condo, 1-15-2, Pantai Dalam, 59200, Kuala Lumpur, Malaysia, kuala lumpur, malaysia",
        merchantContactNo: "0123456789",
        deliveryText: null,
        outOfCoverage: false,
        merchantDeliveryText: "Order delivered:|04:20 PM, Sat, 24 Jul",
        orderDeliveryText: "",
        deliveryProvider: "MatDespatch",
        itemNo: 1,
        trackOrderRecord: {
            orderId: "MBBOR111111111217273",
            orderStatus: 1,
            deliveryStatus: "1000",
            orderStatusText: "Order Completed",
            deliveryStatusText: "Order completed",
            deliveryOrderId: "B78D03D6-6B08-4722-9262-8A65B716DF43",
            consignmentNo: "DM004605M",
            invoiceId: null,
            deliveryPersonnel: null,
            arrival: null,
            riderDetails: {
                name: "Taragas Mahendran",
                phone: "+601130486927",
                vehicleName: "MOTOR1",
                vehicleType: "BIKE",
                vehicleRegNo: "JGT8294",
            },
            arrivingTime: null,
            merchantDeliveryText: null,
            deliveryHistories: [
                {
                    status_code: 1000,
                    status_description: "Order completed",
                    created_at: "2021-07-24T08:20:02.274Z",
                    coord: {
                        lon: 103.6269544,
                        lat: 1.4698755,
                    },
                },
                {
                    status_code: 700,
                    status_description: "Delivered",
                    created_at: "2021-07-24T08:20:02.162Z",
                    coord: {
                        lon: 103.6269544,
                        lat: 1.4698755,
                    },
                },
                {
                    status_code: 625,
                    status_description: "Arrived (Deliver)",
                    created_at: "2021-07-24T08:19:20.384Z",
                    coord: {
                        lon: 103.6275646,
                        lat: 1.4696635,
                    },
                },
                {
                    status_code: 600,
                    status_description: "In transit",
                    created_at: "2021-07-24T08:19:12.406Z",
                    coord: {
                        lon: 103.6275646,
                        lat: 1.4696635,
                    },
                },
                {
                    status_code: 500,
                    status_description: "Collected",
                    created_at: "2021-07-24T08:18:51.974Z",
                    coord: {
                        lon: 103.6275646,
                        lat: 1.4696635,
                    },
                },
                {
                    status_code: 450,
                    status_description: "Arrived for pick-up",
                    created_at: "2021-07-24T08:18:25.350Z",
                    coord: {
                        lon: 103.6275646,
                        lat: 1.4696635,
                    },
                },
                {
                    status_code: 400,
                    status_description: "In transit for pick-up",
                    created_at: "2021-07-24T08:18:11.672Z",
                    coord: {
                        lon: 103.6275646,
                        lat: 1.4696635,
                    },
                },
                {
                    status_code: 200,
                    status_description: "Pending for collection",
                    created_at: "2021-07-21T06:01:56.767Z",
                    coord: {
                        lon: 101.6939126,
                        lat: 3.1819688,
                    },
                },
                {
                    status_code: 100,
                    status_description: "Record created",
                    created_at: "2021-07-21T06:01:39.949Z",
                    coord: {},
                },
            ],
            deliveryMap: "https://demo.delyva.app/customer/rmap?trackingNo=DM004605M&refer=SSL",
            isMap: false,
        },
    },
};

// Self-pickup
export const Request1 = {
    orderId: "MBBOR111111111217462",
    isMerchant: true,
};

export const Response2 = {
    message: "success",
    code: 200,
    challenge: null,
    result: {
        code: 200,
        status: "QR000",
        text: "success",
        recipientName: null,
        products: [
            {
                productId: "MKPRD1000660",
                name: "Menu 1",
                imagePaths: null,
                logo: null,
                priceAmount: null,
                currency: null,
                suitableBike: false,
                sku: null,
                shortDesc: null,
                longDesc: null,
                size: null,
                weight: null,
                categoryName: "Automotive",
                updateDate: null,
                deliveryServiceCode: null,
                outletAddress:
                    "Berjaya Times Square, sefsefse, Imbi, Federal Territory of Kuala Lumpur",
                merchantContactNo: "0125405196",
                outOfCoverage: null,
                image: "https://test.vts.maybank.com.my:8553/api/v1/mobile/Images/MBUAT1205412_Picture_.jpeg",
                netAmtWithoutDeliveryAmt: 5.0,
                orderDetailId: 208593,
                totalAmt: "5.00",
                quantity: 1,
                avail: false,
            },
        ],
        addressDetail: {
            addressLine1: null,
            addressLine2: null,
            addressLine3: null,
            city: null,
            state: null,
            postcode: null,
            contactNo: "0121231234",
            email: "iven.lai@maybank.com",
            type: null,
            addressFlag: null,
            deliveryAddress: null,
            address: null,
        },
        deliveryType: "Self-Pickup",
        categoryId: null,
        merchantId: "MBUAT1205412",
        merchantName: "DaneMerchant001",
        merchantPhNo: null,
        merchantAddress: null,
        promoCode: null,
        totalWeight: null,
        deliveryAmount: 0.0,
        subTotalAmount: null,
        totalPaymentAmount: null,
        orderId: "MBBOR111111111217462",
        customerId: "160000007000243906",
        customerName: "Jon",
        transactionRefno: "MBUAT111111111437457",
        customerReferenceNo: null,
        orderNo: null,
        createdDate: "2021-09-02T18:34:39.317Z",
        netAmt: 5.0,
        discountAmt: 5.0,
        finalAmt: 0.0,
        orderStatus: 3,
        deliveryStatus: null,
        deliveryId: 2,
        outletAddress: "Berjaya Times Square, sefsefse, Imbi, Federal Territory of Kuala Lumpur",
        merchantContactNo: "0125405196",
        deliveryText: "FREE",
        outOfCoverage: null,
        merchantDeliveryText: "Customer Self Pick-up by:|07:04 PM, Thu, 02 Sep",
        orderDeliveryText: "Order confirmed for pick up",
        deliveryProvider: null,
        itemNo: 1,
        trackOrderRecord: null,
    },
};

// Merchant delivery
const Request2 = {
    orderId: "MBBOR111111111217433",
    isMerchant: true,
};

export const Response3 = {
    message: "success",
    code: 200,
    challenge: null,
    result: {
        code: 200,
        status: "QR000",
        text: "success",
        recipientName: null,
        products: [
            {
                productId: "MKPRD1000943",
                name: "Chocolate",
                imagePaths: null,
                logo: null,
                priceAmount: null,
                currency: null,
                suitableBike: false,
                sku: null,
                shortDesc: null,
                longDesc: null,
                size: null,
                weight: null,
                categoryName: "Health & Beauty",
                updateDate: "2021-09-01T10:28:20.270Z",
                deliveryServiceCode: null,
                outletAddress: "12,Gold coast, Persiaran Bayan Indah, pulau pinang, Pulau Pinang",
                merchantContactNo: "+4411117865",
                outOfCoverage: null,
                image: "https://test.vts.maybank.com.my:8553/api/v1/mobile/Images/MBUAT1205457.png",
                netAmtWithoutDeliveryAmt: 10.0,
                orderDetailId: 208562,
                totalAmt: "10.00",
                quantity: 1,
                avail: false,
            },
        ],
        addressDetail: {
            addressLine1: null,
            addressLine2: null,
            addressLine3: null,
            city: null,
            state: "PULAU PINANG",
            postcode: "11900",
            contactNo: "0176654678",
            email: "Satish.inoesis@gmail.com",
            type: null,
            addressFlag: null,
            deliveryAddress: null,
            address: "A-6-9 Persiaran Bayan indah",
        },
        deliveryType: "Merchant  Delivery",
        categoryId: null,
        merchantId: "MBUAT1205457",
        merchantName: "TEST5050 A",
        merchantPhNo: null,
        merchantAddress: null,
        promoCode: null,
        totalWeight: null,
        deliveryAmount: 10.0,
        subTotalAmount: null,
        totalPaymentAmount: null,
        orderId: "MBBOR111111111217433",
        customerId: "160000007000064948",
        customerName: "Testfor 5050",
        transactionRefno: "MBUAT111111111437385",
        customerReferenceNo: null,
        orderNo: null,
        createdDate: "2021-09-01T10:28:19.313Z",
        netAmt: 20.0,
        discountAmt: 0.0,
        finalAmt: 10.0,
        orderStatus: 0,
        deliveryStatus: null,
        deliveryId: 3,
        outletAddress: "12,Gold coast, Persiaran Bayan Indah, pulau pinang, Pulau Pinang",
        merchantContactNo: "+4411117865",
        deliveryText: null,
        outOfCoverage: null,
        merchantDeliveryText: null,
        orderDeliveryText: "Cancelled order",
        deliveryProvider: null,
        itemNo: 1,
        trackOrderRecord: null,
    },
};

// Email
const Request3 = {
    orderId: "MBBOR111111111217411",
    isMerchant: true,
};

export const Response4 = {
    message: "success",
    code: 200,
    challenge: null,
    result: {
        code: 200,
        status: "QR000",
        text: "success",
        recipientName: null,
        products: [
            {
                productId: "MKPRD1000722",
                name: "sassss",
                imagePaths: null,
                logo: null,
                priceAmount: null,
                currency: null,
                suitableBike: false,
                sku: null,
                shortDesc: null,
                longDesc: null,
                size: null,
                weight: null,
                categoryName: "Entertainment test",
                updateDate: "2021-09-08T15:53:03.427Z",
                deliveryServiceCode: null,
                outletAddress: "TEST 2021, no. 100, Lebuh Bandar Utama, Bandar Utama, Selangor",
                merchantContactNo: "0123456799",
                outOfCoverage: null,
                image: "https://test.vts.maybank.com.my:8553/api/v1/mobile/Images/MBUAT1205406.png",
                netAmtWithoutDeliveryAmt: 1.23,
                orderDetailId: 208540,
                totalAmt: "1.23",
                quantity: 1,
                avail: false,
            },
        ],
        addressDetail: {
            addressLine1: null,
            addressLine2: null,
            addressLine3: null,
            city: null,
            state: null,
            postcode: null,
            contactNo: "0105195828",
            email: "samudraladivya@gmail.com",
            type: null,
            addressFlag: null,
            deliveryAddress: null,
            address: null,
        },
        deliveryType: "Email",
        categoryId: null,
        merchantId: "MBUAT1205406",
        merchantName: "TEST 2021 A",
        merchantPhNo: null,
        merchantAddress: null,
        promoCode: null,
        totalWeight: null,
        deliveryAmount: 0.0,
        subTotalAmount: null,
        totalPaymentAmount: null,
        orderId: "MBBOR111111111217411",
        customerId: "160000007000310416",
        customerName: "Divya",
        transactionRefno: "MBUAT111111111437327",
        customerReferenceNo: "172630115Q",
        orderNo: "172630115Q",
        createdDate: "2021-08-30T11:57:16.723Z",
        netAmt: 1.23,
        discountAmt: 0.0,
        finalAmt: 1.23,
        orderStatus: 1,
        deliveryStatus: null,
        deliveryId: 4,
        outletAddress: "TEST 2021, no. 100, Lebuh Bandar Utama, Bandar Utama, Selangor",
        merchantContactNo: "0123456799",
        deliveryText: "FREE",
        outOfCoverage: null,
        merchantDeliveryText: "Order Completed:|03:53 PM, Wed, 08 Sep",
        orderDeliveryText: "Order completed",
        deliveryProvider: null,
        itemNo: 1,
        trackOrderRecord: null,
    },
};
