/* eslint-disable react-native/no-color-literals */
import { StyleSheet, Dimensions, Platform } from "react-native";
export const blueBackgroundColor = "#f8f5f3";

export const window = Dimensions.get("window");

export const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
    amountView9: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 1,
        marginLeft: 5,
        height: 30,
        width: "100%",
        // backgroundColor: "#fff",
        flex: 1,
    },
    secure2uRowView: {
        flex: 2.8,
        flexDirection: "column",
        height: 55,
        justifyContent: "center",
        marginRight: 60,
        marginTop: 35,
    },
    tranTypeLabel: {
        color: "gray",
        flex: 1.8,
        fontFamily: "montserrat",
        fontSize: 13,
        fontWeight: "normal",
        marginLeft: 50,
    },
    tranTypeValueLabel: {
        color: "#fff",
        flex: 1,
        fontFamily: "montserrat",
        fontSize: 13,
        fontWeight: "bold",
        marginRight: 0,
        textAlign: "right",
    },
    detailSwitchView: {
        height: 38,
        marginLeft: 0,
        marginRight: 0,
        marginTop: 16,
        shadowColor: "#d9d9d9",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 1,
        shadowRadius: 4,
        width: "85%",
    },
    bg: {
        height: "100%",
        marginLeft: 0,
        marginRight: 0,
        marginTop: 0,
        width: "100%",
    },
    bgContainer: { backgroundColor: "blue", marginBottom: 1, marginTop: 10, width: "100%" },
    block: { flexDirection: "row", marginTop: 30 },
    blockDateRow: { flexDirection: "row", marginTop: 10 },
    block1: { marginTop: 30, flexDirection: "column" },
    blockContainer: {
        flexDirection: "row",

        justifyContent: "flex-start",
        marginRight: 36,
        marginTop: 17,
    },
    blockContainer4: {
        flexDirection: "row",

        justifyContent: "space-around",
        marginRight: 36,
        marginTop: 17,
    },
    blockContainer1: {
        flexDirection: "row",

        justifyContent: "space-around",
        marginRight: 36,
        marginTop: 17,
    },
    buyViewButtonView: {
        width: "50%",
    },
    checkTrainText: {
        marginTop: 36,
        width: "80%",
    },
    circleImageView: {
        alignContent: "center",
        alignItems: "center",
        backgroundColor: "transparent",
        borderColor: "transparent",
        borderRadius: 57,
        borderWidth: 1,
        flexDirection: "row",
        height: 57,
        justifyContent: "center",
        marginLeft: 0,
        marginTop: 0,
        overflow: "hidden",
        width: 57,
    },
    container: { backgroundColor: "transparent", flex: 1, width: "100%" },
    containerAmountTitle: {
        alignContent: "center",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 35,
        marginTop: 10,
        width: "83%",
    },
    containerAmountTitle1: {
        alignContent: "center",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 35,
        marginTop: 25,
        width: "83%",
    },
    containerBlockView: {
        flex: 1,
        flexDirection: "column",
        backgroundColor: "#f8f8f8",
    },
    containerBottom: {
        alignItems: "flex-start",
        flex: 1,
        flexDirection: "column",
        justifyContent: "flex-start",
        width: "100%",
        height: "100%",
    },
    containerDesc: {
        marginBottom: 20,
        marginHorizontal: width * 0.12,
    },
    containerInner: {
        alignItems: "flex-start",
        flex: 1,
        flexDirection: "column",
        justifyContent: "flex-start",
        marginLeft: 36,
        marginRight: 36,
        width: "100%",
        height: "100%",
    },
    containerInner1: {
        alignItems: "flex-start",
        flex: 1,
        flexDirection: "column",
        justifyContent: "flex-start",
        marginLeft: 36,
        marginRight: 36,
        width: "83%",
        height: "100%",
    },
    containerInnerView1: {
        flexDirection: "column",

        flex: 1,
        width: "100%",
        height: "100%",
    },
    containerInnerView3: {
        flexDirection: "column",
        flex: 1,
        width: "100%",
        height: "100%",
    },
    containerInnerView4: {
        flexDirection: "column",
        height: "100%",
        marginTop: 12,
        width: "100%",
    },

    containerInnerView5: {
        flexDirection: "column",
        height: "100%",
        marginTop: 5,
        width: "100%",
    },

    dotsView4: {
        flexDirection: "column",
        alignContent: "center",
        alignItems: "center",
        justifyContent: "center",

        height: 20,
        marginTop: 25,
        width: "100%",
    },
    containerLightGrayView: {
        backgroundColor: "#f8f8f8",
        flex: 1,
    },
    containerNoteTitle: {
        marginTop: 25,
    },
    containerOfferAmountInner: {
        flexDirection: "column",
        height: 20,
        position: "absolute",
    },
    containerOfferAmountTitle: {
        alignContent: "center",
        alignItems: "center",
        justifyContent: "center",
        marginTop: 17,
        width: "83%",
    },
    containerTitle: {
        marginTop: 12,
    },
    containerTitleFirst: {
        marginTop: "20%",
    },
    containerTypeTitle: {
        marginTop: 24,
    },
    containerView: {
        backgroundColor: "transparent",
        flex: 1,
    },
    containerViewScrollView: {
        flex: 1,
        flexDirection: "column",
    },
    contentContainer: {
        alignContent: "center",
        alignItems: "center",
        flex: 1,
    },
    countTextView: { marginTop: 5 },
    descriptionContainer: {
        justifyContent: "flex-start",
        marginLeft: 36,
        marginRight: 36,
        marginTop: 10,
    },
    detailSwitchContainer: {
        shadowColor: "#d9d9d9",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 1,
        shadowRadius: 4,
    },
    footerButtonView: {
        width: "100%",
    },
    footerInner: {
        flexDirection: "row",
        justifyContent: "center",
    },
    footerNoContentImage: {
        alignItems: "center",
        flex: 1,
        flexDirection: "column",
        justifyContent: "flex-start",
        width: "100%",
        height: "100%",
    },
    footerNoContentView: {
        backgroundColor: "transparent",
        flex: 1,
    },
    footerTextView: {
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 40,
        marginLeft: 36,
        marginRight: 36,
    },
    footerTextView1: {
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 16,
        marginLeft: 36,
        marginRight: 36,
    },
    footerView: {
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 20,
        marginLeft: 36,
        marginRight: 36,
    },
    hisSelect: { color: "#000000", margin: 10, marginBottom: 5, fontWeight: "900", fontSize: 13 },
    hisTextContainer: { marginTop: 2, alignItems: "center", flexDirection: "row" },
    hisUnselect: { color: "#8f8f8f", margin: 10, marginBottom: 5, fontWeight: "900", fontSize: 13 },
    imageContainer: { alignItems: "center", justifyContent: "center", marginTop: 20 },
    imageText: { color: "#000000", fontSize: 20, fontWeight: "400" },
    increaseButtonView: {},
    increaseView: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 26,
        width: "83%",
    },
    newTransferCircle: {
        alignContent: "center",
        alignItems: "center",
        backgroundColor: "transparent",
        borderRadius: 57,
        flexDirection: "row",
        height: 57,
        justifyContent: "center",
        width: 57,
    },
    newTransferViewInner1: {
        flexDirection: "column",
        marginTop: 100,
    },

    offerStrickLine: {
        alignContent: "center",
        alignItems: "center",
        backgroundColor: "#000000",
        height: 1.3,
        justifyContent: "center",
        marginTop: -8,
        width: "100%",
    },
    roundButtonWithImage: {
        marginTop: 24,
        width: "80%",
    },
    secondView: {
        marginTop: 24,
    },
    setupContainer: { marginLeft: 30, marginTop: 30 },
    subLeftText: {
        color: "#000000",
        fontFamily: "montserrat",
        fontSize: 13,
        fontStyle: "normal",
        fontWeight: "normal",
        letterSpacing: 0,
        lineHeight: 19,
        opacity: 0.5,
        textAlign: "left",
    },
    subRightText: {
        color: "#000000",
        fontFamily: "montserrat",
        fontSize: 13,
        fontStyle: "normal",
        fontWeight: "600",
        letterSpacing: 0,
        lineHeight: 19,
        textAlign: "right",
    },
    summaryAmountCoverView: {
        backgroundColor: "#eaeaea",
        borderRadius: 8,
        flexDirection: "column",
        height: 78,
        justifyContent: "center",
        marginBottom: 15.5,
        marginTop: 9,
        width: "83%",
    },
    summaryAmountTextView: {
        flexDirection: "row",
        marginLeft: 16,
    },
    summaryIcon: {
        height: 24,
        paddingTop: 6,
        width: 24,
    },
    summaryRowInnerView: {
        flexDirection: "column",
        justifyContent: "flex-start",
        marginBottom: 15.5,
        marginTop: 6.5,
        width: "83%",
    },
    summaryRowLine: {
        backgroundColor: "#eaeaea",
        borderColor: "#eaeaea",
        borderStyle: "solid",
        height: 1,
        justifyContent: "center",
        marginTop: 14.5,
        width: "100%",
    },
    summaryRowView: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "flex-start",
        width: "100%",
    },
    summaryTextView: {
        marginLeft: 16,
        marginRight: 52,
    },
    summaryTotalLabelView: {
        justifyContent: "center",
        marginLeft: 32,
    },
    summaryValueTextView: { marginTop: 5 },
    summaryValueTextView1: { marginTop: 15 },
    ticketCountView: {
        flexDirection: "row",
        marginTop: 16,
        width: "83%",
    },
    titleContainer: {
        justifyContent: "flex-start",
        marginTop: 10,
        marginRight: 15,
        paddingRight: 15,
    },
    titleText: {
        color: "#000000",
        fontFamily: "montserrat",
        fontSize: 20,
        fontStyle: "normal",
        fontWeight: "300",
        letterSpacing: 0,
        lineHeight: 30,
    },
    topNoContentView: {
        backgroundColor: "transparent",
        height: (height - 153) / 2,
        width: width,
    },
    actionItem: {
        backgroundColor: "#fff",
        borderRadius: 10 / 2,
        flexDirection: "column",
        height: 381,
        marginLeft: 23,
        marginRight: 3,
        width: "92%",
    },
    actionItemImage: {
        height: 77,
        marginLeft: 16,
        marginTop: 51,
        width: 77,
    },
    actionItemTitle: {
        color: "#000000",
        fontSize: 17,
        fontWeight: "bold",
        marginLeft: 16,
        marginTop: 18,
    },
    secure2uFirstRowView: {
        alignItems: "center",
        flexDirection: "row",
        height: 30,
        marginLeft: 16,
        marginRight: 16,
        marginTop: 10,
        width: "100%",
        // backgroundColor: "#fff",
        flex: 1,
    },
    secure2uRowView: {
        flex: 2.8,
        flexDirection: "column",
        height: 55,
        justifyContent: "center",
        marginRight: 60,
        marginTop: 35,
    },
});
