import { StyleSheet, Dimensions } from "react-native";

import {
    DISABLED_DROPDOWN_TEXT,
    OFF_WHITE,
    GREEN,
    VERY_LIGHT_GREY,
    PRIMARY_YELLO,
    WHITE,
    GREY,
    BLACK,
    ROYAL_BLUE,
    SWITCH_GREY,
    TRANSPARENT,
    RED,
    MEDIUM_GREY,
} from "@constants/colors";

const { height, width } = Dimensions.get("window");

const FLEX_START = "flex-start";
const SPACE_BETWEEN = "space-between";
const MONTSERRAT_BOLD = "Montserrat-SemiBold";
const DESC_COLOR = "#3b3b41";
const DESC_COLOR2 = "#414141";

export default StyleSheet.create({
    accFirstView: {
        flex: 1,
    },
    accHorMainView: {
        flexDirection: "row",
        height: 100,
        justifyContent: "center",
        marginLeft: 20,
        marginRight: 20,
        width: 280,
    },
    accSecondView: {
        flex: 1,
        flexDirection: "column",
        justifyContent: FLEX_START,
    },
    accountBalanceLabel: {
        color: BLACK,
        fontSize: 13,
        fontWeight: "900",
        marginLeft: 20,
        marginTop: 8,
    },
    accountDetailsView: {
        flexDirection: "row",
        justifyContent: FLEX_START,
        marginTop: 0,
    },
    accountFromLabel: {
        color: GREY,
        fontSize: 14,
        fontWeight: "500",
        marginLeft: 20,
        marginTop: 10,
    },
    accountItemImage: {
        height: 120,
        marginTop: 2,
        width: 149,
    },
    accountNameLabel: {
        color: BLACK,
        fontSize: 13,
        fontWeight: "900",
        marginLeft: 20,
        marginTop: 5,
    },
    accountNoView: {
        alignItems: "center",
        flexDirection: "row",
        height: 60,
        marginLeft: "14%",
        marginTop: 60,
        width: "100%",
    },
    accountNoViewTransfer: {
        alignItems: "center",
        flexDirection: "row",
        marginLeft: 35,
        marginTop: 30,
        width: "100%",
    },
    accountNumberSmall: {
        color: BLACK,
        fontSize: 10,
        fontWeight: "900",
        marginLeft: 12,
        marginTop: 34,
    },
    accountsFlatlist: {
        marginBottom: 24,
        marginTop: 12,
    },
    addFavouritesView: {
        marginLeft: 0,
        marginTop: 10,
    },
    alerBillView: {
        flexDirection: "row",
        height: (20 * height) / 667,
        justifyContent: "center",
        marginBottom: (22 * height) / 667,
        marginLeft: (35 * width) / 375,
        marginTop: (10 * height) / 667,
        width: (305 * width) / 375,
    },
    amountCenter: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        marginLeft: 9,
        marginTop: 16,
    },
    amountCenter2: {
        alignItems: "center",
        flexDirection: "column",
        justifyContent: "center",
        marginLeft: 9,
        marginTop: 12,
    },
    amountCenterConfirm: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 37,
        marginLeft: 0,
        marginTop: 16,
    },

    amountDisLabel: {
        color: BLACK,
        fontSize: 20,
        fontWeight: "800",
    },

    amountDisLabelSmall: {
        color: BLACK,
        fontFamily: "montserrat",
        fontSize: 11,
        fontWeight: "100",
    },
    amountTextBlack: {
        color: BLACK,
        fontFamily: "montserrat",
        fontSize: 23,
        fontStyle: "normal",
        fontWeight: "bold",
        letterSpacing: -0.43,
        lineHeight: 33,
    },
    amountTextBlack1: {
        color: BLACK,
        fontFamily: "montserrat",
        fontSize: 23,
        fontStyle: "normal",
        fontWeight: "normal",
        letterSpacing: -0.43,
        lineHeight: 33,
        width: "80%",
    },
    amountTextBlue: {
        color: ROYAL_BLUE,
        fontFamily: "montserrat",
        fontSize: 23,
        fontStyle: "normal",
        fontWeight: "bold",
        letterSpacing: -0.43,
        lineHeight: 33,
    },
    amountValueView: {
        alignItems: "center",
        flexDirection: "row",
        height: 60,
        marginLeft: 35,
        marginTop: 23,
        width: "95%",
    },
    amountView1: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 1,
        marginLeft: 5,
        height: 30,
        width: "100%",
        // backgroundcolor: WHITE,
        flex: 1,
    },
    amountView10: {
        alignItems: "center",
        flexDirection: "row",
        marginTop: 15,
        marginLeft: 5,
        height: 30,
        width: "100%",
        // backgroundcolor: WHITE,
        flex: 1,
    },
    amountView2: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 40,
        marginLeft: 5,
        height: 30,
        width: "100%",
        // backgroundcolor: WHITE,
        flex: 1,
    },

    amountView9: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 1,
        marginLeft: 5,
        height: 30,
        width: "100%",
        // backgroundcolor: WHITE,
        flex: 1,
    },
    amountViewTransfer: {
        alignItems: "center",
        flexDirection: "row",
        marginTop: 4,
        width: "100%",
    },
    amountViewTransfer1: {
        alignItems: "center",
        flexDirection: "row",
        marginTop: 10,
        width: "100%",
    },
    amtValueLabel: {
        color: BLACK,
        flex: 1.5,
        fontFamily: "montserrat",
        fontSize: 13,
        fontWeight: "bold",
        marginRight: 0,
        textAlign: "right",
    },
    amtValueLabel2: {
        color: BLACK,
        flex: 1.5,
        fontFamily: "montserrat",
        fontSize: 13,
        fontWeight: "bold",
        marginRight: 0,
        textAlign: "right",
    },
    autoDebitView: {
        backgroundColor: RED,
        height: (41 * height) / 667,
        marginBottom: (70 * height) / 667,
        marginLeft: (35 * width) / 375,
        width: (305 * width) / 375,
    },
    backToButtonOneView1: {
        marginLeft: 40,
        marginTop: -90,
    },
    backToButtonView: {
        marginLeft: 40,
        marginTop: 0,
    },
    backToButtonView1: {
        marginLeft: 40,
        marginTop: -20,
    },
    backToButtonViewDown: {
        marginLeft: 40,
        marginTop: 70,
    },
    bankDetailsValueView: {
        flex: 2.8,
        flexDirection: "column",
        height: 55,
        justifyContent: "center",
        marginRight: 55,
    },
    bankDetailsView: {
        flexDirection: "row",
        justifyContent: FLEX_START,
        marginTop: 31,
    },
    block: {
        flexDirection: "column",
        flex: 1,
    },
    blockCenter: {
        alignItems: "center",
        flexDirection: "column",
        flex: 1,
    },
    blockMargin: {
        marginLeft: 24,
        marginRight: 24,
    },
    blockAccountView: {
        marginLeft: 24,
    },
    blockConfirm: {
        flexDirection: "column",
        flex: 1,
    },
    blockInner: {
        flexDirection: "column",
        flex: 1,
        marginLeft: 24,
        marginRight: 24,
    },
    blockNew: {
        flexDirection: "column",
        flex: 1,
        paddingHorizontal: 24,
    },
    blockS2uAuth: {
        flexDirection: "column",
        flex: 1,
        marginLeft: 36,
        marginRight: 36,
    },
    blockS2uAuth1: {
        flexDirection: "column",
        flex: 1,
        marginLeft: 0,
        marginRight: 0,
    },
    blockSpace: {
        flexDirection: "column",
        flex: 1,
        alignContent: SPACE_BETWEEN,
        height: height - 200,
    },
    blurContainer: {
        alignItems: "center",
        bottom: 0,
        flex: 1,
        justifyContent: "center",
        left: 0,
        position: "absolute",
        right: 0,
        top: 0,
    },
    bottomBtnMargin: {
        marginBottom: 30,
    },
    bottomTitleView: {
        marginLeft: 0,
    },
    bottomTransferView: {
        flexDirection: "column",
        justifyContent: "center",
        marginBottom: 20,
        marginHorizontal: -24,
    },
    bottomView: {
        flexDirection: "column",
        height: 171,
        justifyContent: "center",
        marginBottom: 2,
        marginTop: 0,
    },
    buttonViewInner: {
        flexDirection: "row",
        justifyContent: "center",
        width: 200,
    },
    buttonViewInner1: {
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        width: 250,
    },
    calculatorButton: {
        flexDirection: "row",
        flex: 1,
        //backgroundColor:"gray",
        alignContent: "center",
        justifyContent: "center",
        alignItems: "center",
    },
    calculatorButtonImage: {
        flexDirection: "row",
        height: 13,
        width: 13,
    },
    calculatorButtonText: {
        color: WHITE,
        fontSize: 29,
    },
    calculatorMain: {
        backgroundColor: BLACK,
        flexDirection: "row",
        height: 60,

        marginLeft: 0,
        width: "100%",
    },

    cardImageSmall: {
        elevation: 8,
        height: 75,
        shadowColor: BLACK,
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 4.65,
        width: 100,
    },
    cardImageSmall1: {
        height: 60,
        width: 85,
    },
    cardNameLabel: {
        color: BLACK,
        flex: 1.5,
        fontFamily: "montserrat",
        fontSize: 13,
        fontWeight: "normal",
        marginLeft: 50,
    },
    cardNameLabel2: {
        color: BLACK,
        flex: 1.8,
        fontFamily: "montserrat",
        fontSize: 13,
        fontWeight: "normal",
        marginLeft: 50,
    },
    cardSmallContainerCenter: {
        alignContent: "center",
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 0,
        marginTop: 0,
    },
    cardSmallContainerColumnCenter3: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "column",
        justifyContent: "center",
    },
    cardSmallContainerCenter1: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 10,
        marginTop: 3,
    },
    cardSmallContainerColumnCenter: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "column",
        justifyContent: "center",
        marginBottom: 0,
        marginTop: 0,
    },

    cardSmallContainerColumnCenter2: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "column",
        justifyContent: "center",
        marginBottom: 54,
        marginTop: 0,
    },
    commonInput1: {
        alignItems: "stretch",
        color: BLACK,
        flex: 1,
        flexDirection: "column",
        fontFamily: "Montserrat",
        fontSize: 15,
        fontStyle: "normal",
        fontWeight: "300",
        justifyContent: "center",
        letterSpacing: 0,
        lineHeight: 33,
        textAlign: "center",
    },
    commonInput2: {
        alignItems: "stretch",
        color: BLACK,
        flex: 1,
        flexDirection: "column",
        fontFamily: "montserrat",
        fontSize: 18,
        fontStyle: "normal",
        fontWeight: "300",
        justifyContent: "center",
        letterSpacing: 0,
        lineHeight: 2,
        textAlign: "center",
    },
    commonInput3: {
        alignItems: "stretch",
        color: BLACK,
        flex: 1,
        flexDirection: "column",
        fontFamily: "montserrat",
        fontSize: 18,
        fontStyle: "normal",
        fontWeight: "300",
        height: 70,
        justifyContent: "center",
        letterSpacing: 0,
        lineHeight: 2,
        textAlign: "center",
    },
    commonInputConfirm: {
        color: ROYAL_BLUE,
        fontFamily: MONTSERRAT_BOLD,
        fontSize: 14,
        fontWeight: "normal",
        marginRight: 0,
        marginTop: -13,
        minWidth: 90,
    },
    commonInputConfirmIos: {
        color: BLACK,
        fontFamily: MONTSERRAT_BOLD,
        fontSize: 14,
        marginTop: 0,
        minWidth: 70,
    },

    commonInputConfirmIosText: {
        color: ROYAL_BLUE,
        fontFamily: MONTSERRAT_BOLD,
        fontSize: 14,
        // marginRight: -4,
        marginTop: 0,
        minWidth: 70,
    },
    /**
     * Font weight in android for text input need to be normal.
     * so the usage correct font family with weight is important
     * https://github.com/facebook/react-native/issues/18820
     */
    commonInputConfirmText: {
        color: ROYAL_BLUE,
        fontFamily: MONTSERRAT_BOLD,
        fontSize: 14,
        fontStyle: "normal",
        fontWeight: "normal",
        marginRight: 0,
        marginTop: -13,
        minWidth: 90,
    },
    confirmButtonView: {
        marginLeft: 25,
        marginTop: 150,
    },
    confirmView1: {
        flexDirection: "row",
        justifyContent: "center",
        margin: 24,
        marginTop: 0,
    },

    container: {
        backgroundColor: MEDIUM_GREY,
        flex: 1,
        width: "100%",
    },
    containerAddTransfer: {
        flex: 1,
        paddingHorizontal: 35,
        width,
    },
    containerBlack: {
        //backgroundColor: "#424242",
        flex: 1,
        width: "100%",
    },
    containerDuitScreen: {
        flex: 1,
        paddingHorizontal: 36,
        width: "100%",
    },
    containerLight: {
        backgroundColor: OFF_WHITE,
        flex: 1,
        width: "100%",
    },
    containerTrans: {
        flex: 1,
        width,
    },
    containerWhiteLight: {
        flex: 1,
        width,
    },

    contentContainerStyle: {
        flexGrow: 1,
        flex: 1,
    },
    contentTab: {
        flex: 1,
        flexDirection: "column",
    },
    dateText: {
        lineHeight: (17 * height) / 667,
        backgroundColor: GREEN,
        marginTop: (-18 * height) / 667,
        fontFamily: "montserrat",
        fontSize: 11,
        width: (305 * width) / 375,
        textAlign: "center",
    },
    dateTimeLabel: {
        color: BLACK,
        flex: 1,
        fontFamily: "montserrat",
        fontSize: 13,
        fontWeight: "normal",
        marginLeft: 50,
    },
    dateTimeLabel1: {
        color: BLACK,
        flex: 1.5,
        fontFamily: "montserrat",
        fontSize: 13,
        fontWeight: "normal",
        marginLeft: 50,
    },
    dateView: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 15,
    },
    dateView1: {
        flexDirection: "row",
        justifyContent: FLEX_START,
        marginLeft: 35,
        marginTop: 25,
        width: "100%",
    },
    dateViewInner: {
        flexDirection: "row",
        justifyContent: "center",
        width: 230,
    },
    dateViewInnerBig: {
        flexDirection: "row",
        justifyContent: FLEX_START,
        width: "100%",
    },
    descContainer1: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 20,
    },
    descContainer2: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "column",
        justifyContent: "center",
        marginTop: 5,
    },
    descContainer2Error: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "column",
        justifyContent: "center",
        marginTop: 5,
    },
    descContainerSuccess1: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 60,
    },
    descTextNew1: {
        color: DESC_COLOR,
        fontSize: 13,
        fontWeight: "bold",
    },
    descTextNew2: {
        alignContent: "center",
        alignItems: "center",
        alignSelf: "center",
        color: DESC_COLOR,
        fontSize: 15,
        fontWeight: "normal",
        lineHeight: 23,
        textAlign: "center",
    },
    descTextNewError: {
        alignContent: "center",
        alignItems: "center",
        alignSelf: "center",
        color: RED,
        fontSize: 15,
        fontWeight: "normal",
        lineHeight: 23,
        textAlign: "center",
    },
    descTextNormal: {
        alignContent: "center",
        alignItems: "center",
        alignSelf: "center",
        color: DESC_COLOR,
        fontSize: 15,
        fontWeight: "normal",
        lineHeight: 23,
        textAlign: "center",
    },
    descTextNormalSmall: {
        alignContent: "center",
        alignItems: "center",
        alignSelf: "center",
        color: DESC_COLOR,
        fontSize: 10,
        fontWeight: "normal",
        lineHeight: 23,
        textAlign: "center",
    },
    descriptionAmtContainer2: {
        justifyContent: FLEX_START,
        marginBottom: 40,
        marginLeft: 35,
        marginRight: 35,
        marginTop: 25,
    },
    descriptionContainer: {
        justifyContent: FLEX_START,
        marginLeft: 35,
        marginRight: 50,
        marginTop: 2,
    },
    descriptionContainer1: {
        justifyContent: FLEX_START,
        marginLeft: 60,
        marginRight: 50,
        marginTop: 40,
    },
    descriptionContainer11: {
        justifyContent: FLEX_START,
        marginLeft: 50,
        marginRight: 50,
        marginTop: 2,
    },
    descriptionContainer2: {
        justifyContent: FLEX_START,
        marginLeft: 52,
        marginRight: 50,
        marginTop: 35,
    },
    descriptionContainer2Center: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 4,
    },
    descriptionContainer5: {
        justifyContent: FLEX_START,
        marginLeft: 35,
        marginRight: 50,
        marginTop: 8,
    },
    descriptionContainer7: {
        justifyContent: FLEX_START,
        marginLeft: 35,
        marginRight: 50,
        marginTop: 10,
    },
    descriptionContainer8: {
        justifyContent: FLEX_START,
        marginLeft: 35,
        marginRight: 50,
        marginTop: 20,
    },
    descriptionContainerAmount: {
        marginTop: 26,
    },
    descriptionContainerAmount1: {
        flexDirection: "column",
        marginTop: 26,
    },
    descriptionContainerCenter: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 14,
    },
    descriptionContainerLeft: {
        alignItems: FLEX_START,
        flexDirection: "row",
        justifyContent: FLEX_START,
        marginTop: 1,
    },
    descriptionContainerRM: {
        justifyContent: FLEX_START,
        marginLeft: 12,
        marginRight: 35,
        marginTop: 2,
    },
    descriptionContainerReference: {
        justifyContent: FLEX_START,
        marginLeft: 35,
        marginRight: 50,
        marginTop: 20,
    },
    descriptionContainerReference11: {
        justifyContent: FLEX_START,
        marginLeft: 50,
        marginRight: 50,
        marginTop: 20,
    },
    descriptionContainerTr: {
        justifyContent: FLEX_START,
        marginLeft: 35,
        marginRight: 50,
        marginTop: 2,
    },
    descriptionSecContainer: {
        justifyContent: FLEX_START,
        marginLeft: 60,
        marginRight: 50,
        marginTop: 5,
    },
    descriptionText6: {
        color: DESC_COLOR2,
        fontSize: 17,
        fontWeight: "bold",
    },
    descriptionText9: {
        color: BLACK,
        fontSize: 20,
        fontStyle: "normal",
        fontWeight: "300",
        letterSpacing: 0,
        lineHeight: 30,
    },
    doneButtonView: {},
    downArrowView: {
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 10,
    },
    duitNowAmount: {
        color: BLACK,
        fontSize: 21,
        fontStyle: "normal",
        fontWeight: "bold",
    },
    duitNowAmountFaded: {
        color: VERY_LIGHT_GREY,
        fontSize: 21,
        fontStyle: "normal",
        fontWeight: "bold",
    },
    editIcon: {
        height: 18,
        width: 18,
    },
    editIconView: {
        marginLeft: 10,
        marginTop: 10,
    },
    editIconViewTransfer: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 37,
        marginLeft: 0,
        marginTop: 16,
    },
    editIconViewTransfer2: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 0,
        marginLeft: 0,
        marginTop: 24,
    },
    emptyText2View: {
        marginTop: 8,
    },
    emptyTextView: {
        marginTop: 24,
    },
    enableDuit: {
        flex: 1,
        flexDirection: "row",
        justifyContent: SPACE_BETWEEN,
        marginBottom: 8,
        marginTop: 20,
    },
    rowChild: {
        flex: 1,
        flexDirection: "row",
        justifyContent: SPACE_BETWEEN,
        marginVertical: 10,
    },
    wid70: { width: "70%" },
    autoDebitCard: {
        backgroundColor: WHITE,
        borderRadius: 8,
        flex: 1,
        marginTop: 10,
        paddingHorizontal: 20,
        paddingVertical: 10,
    },
    autoDebitCard2: {
        backgroundColor: WHITE,
        borderRadius: 8,
        flex: 1,
        marginBottom: 20,
        marginTop: 10,
        paddingHorizontal: 20,
        paddingVertical: 10,
    },
    circle: {
        borderRadius: 10,
        height: 19,
        width: 19,
    },
    container2: {
        borderRadius: 11,
        height: 22,
        padding: 1,
        width: 39,
    },
    errorTextView: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "column",
        justifyContent: FLEX_START,
        marginBottom: 0,
        marginLeft: 0,
        marginTop: 8,
    },

    favAccountHolderName: {
        color: ROYAL_BLUE,
        fontSize: 23,
        fontStyle: "normal",
        fontWeight: "bold",
        letterSpacing: 0,
        lineHeight: 21,
    },

    favAccountHolderNameEdited: {
        color: BLACK,
        fontSize: 23,
        fontStyle: "normal",
        fontWeight: "bold",
        letterSpacing: 0,
        lineHeight: 21,
    },

    favFirstItem: {
        alignItems: FLEX_START,
        flexDirection: "column",
        marginTop: 40,
        width: "100%",
    },
    favLogoItem: {
        alignItems: FLEX_START,
        flexDirection: "row",
        marginTop: 32,
        width: "100%",
    },
    favNameItem: {
        alignItems: FLEX_START,
        flexDirection: "row",
        marginTop: 4,
        width: "100%",
    },
    favouriteListView: {
        marginTop: 25,
    },
    firstContainer: {
        flexDirection: "row",
        justifyContent: FLEX_START,
        marginLeft: 35,
        marginTop: 40,
    },
    footerBottomView: {
        height: 36,
        width: "100%",
    },

    footerButton: { marginBottom: 36, paddingHorizontal: 24, width: "100%" },
    footerButton2: { marginBottom: 10, marginTop: 0, paddingHorizontal: 14, width: "100%" },
    footerButtonEmptyView: {
        marginBottom: 22,
        width: "100%",
    },
    footerButtonView: {
        marginBottom: 38,
        marginTop: 8,
        width: "100%",
    },
    footerButtonView22: {
        marginBottom: 16,
        width: "100%",
    },
    footerContainer: {
        flex: 2,
        justifyContent: FLEX_START,
        marginLeft: 60,
        marginTop: 40,
    },
    footerInner: {
        flexDirection: "row",
        justifyContent: "center",
    },
    footerText: {
        fontSize: 14,
        textDecorationLine: "underline",
    },
    footerTextView: {
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 24,
        marginRight: 0,
        marginTop: 24,
    },
    footerView: {
        alignItems: "flex-end",
        bottom: 0,
        flexDirection: "column",
        justifyContent: "center",
        marginBottom: 1,
        marginLeft: "15.5%",
        marginRight: 50,
        position: "absolute",
        width: "90%",
    },
    footerView1: {
        alignItems: FLEX_START,
        bottom: 0,
        flexDirection: "row",
        height: 95,
        justifyContent: FLEX_START,
        marginBottom: 1,
        marginLeft: "15.5%",
        marginRight: 50,
        position: "absolute",
        width: "90%",
    },
    footerView3: {
        bottom: 0,
        position: "absolute",
    },
    footerViewAck: {
        alignItems: "center",
        bottom: 0,
        flexDirection: "column",
        justifyContent: "center",
        marginBottom: 0,
        marginLeft: 36,
        marginRight: 36,
        position: "absolute",
        width: "82%",
    },

    image: {
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        height: 50,
        width: 50,
    },

    imageContainerView: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 18,
    },

    imageTextIntialsView: {
        alignItems: "center",
        backgroundColor: GREY,
        borderColor: WHITE,
        borderRadius: 60 / 2,
        borderWidth: 4,
        height: 60,
        justifyContent: "center",
        width: 60,
    },

    infoImage: {
        height: (20 * height) / 667,
        resizeMode: "contain",
        width: (20 * height) / 667,
    },

    inputCardNoView10: {
        flex: 1.5,
        flexDirection: "column",
        height: 55,
        justifyContent: "center",
        marginRight: 60,
        marginTop: 20,
    },
    inputCardNoView11: {
        flex: 2,
        flexDirection: "column",
        height: 55,
        justifyContent: "center",
        marginRight: 60,
        marginTop: 20,
    },
    inputCardNoView7: {
        flex: 2.8,
        flexDirection: "column",
        height: 55,
        justifyContent: "center",
        marginRight: 60,
        marginTop: 20,
    },
    inputCardNoView8: {
        flex: 2.9,
        flexDirection: "column",
        height: 55,
        justifyContent: "center",
        marginRight: 60,
        marginTop: 30,
    },
    inputCardNoView9: {
        flex: 2.8,
        flexDirection: "column",
        height: 55,
        justifyContent: "center",
        marginRight: 60,
        marginTop: 40,
    },
    inputContainer: {
        alignItems: FLEX_START,
        height: 50,
        justifyContent: "center",
        marginLeft: 40,
        marginTop: 20,
    },

    intialText: {
        height: 22,
        width: 26,
    },
    lineConfirm: {
        backgroundColor: SWITCH_GREY,
        flexDirection: "row",
        height: 1,
        marginTop: 15,
    },
    lineTermsConfirm: {
        backgroundColor: SWITCH_GREY,
        flexDirection: "row",
        height: 1,
        marginTop: 2,
        width: "100%",
    },
    lineView: {
        backgroundColor: GREY,
        flex: 1,
        height: 1.5,
        marginLeft: "12%",
        marginRight: "20%",
        marginTop: 10,
        width: "77%",
    },
    listSearchView: {
        marginTop: 25,
    },

    listTileView: {
        marginTop: 5,
    },

    listView: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "row",
        justifyContent: FLEX_START,
        marginLeft: 0,
        marginTop: 24,
    },
    logoImageConfirm: {
        alignContent: "center",
        alignItems: "center",
        borderRadius: 50,

        elevation: 8,
        flexDirection: "row",
        height: 64,
        justifyContent: "center",
        shadowColor: BLACK,
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 4.65,
        width: 64,
    },
    logoImageFullViewConfirm: {
        alignContent: "center",
        alignItems: "center",
    },
    logoImageReloadConfirm: {
        alignContent: "center",
        alignItems: "center",
        borderColor: WHITE,
        borderRadius: 50,
        borderWidth: 3,
        flexDirection: "row",
        height: 64,
        justifyContent: "center",
        width: 64,
    },
    logoImageViewConfirm: {
        alignContent: "center",
        alignItems: "center",
        borderRadius: 50,
        flexDirection: "row",
        height: 64,

        justifyContent: "center",
        marginLeft: 7,
        marginTop: 8,
        width: 64,
    },
    logoView: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 18,
    },
    maybankCardView: {
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 10,
    },
    nameEditView: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "row",
        justifyContent: FLEX_START,
        marginLeft: 52,
        marginTop: 31,
    },
    nameTextView: {
        alignItems: "center",
        flexDirection: "row",
        height: 60,
        marginLeft: 55,
        marginRight: 55,
        marginTop: 20,
        width: "95%",
    },
    notesInputTransferView: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "row",
        height: 70,
        justifyContent: "center",
        marginBottom: 90,
        marginTop: 5,
        //backgroundColor: "gray"
    },
    notesInputView: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "row",
        height: 70,
        justifyContent: "center",
        marginBottom: 90,
        marginTop: 5,
    },
    notesViewCenter1: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 15,
    },
    notesViewCenter4: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 0,
        width: "100%",
    },
    notesViewCenter5: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 3,
        width: "50%",
    },
    parentBlockConfirm: {
        flexDirection: "column",
        flex: 1,
    },
    payFromtext: {
        marginTop: 10,
    },
    topContainer: { width: "100%", height: "35%", position: "absolute" },
    payLabel: {
        color: BLACK,
        fontFamily: "montserrat",
        fontSize: 20,
        fontStyle: "normal",
        fontWeight: "500",
        letterSpacing: -0.43,
        lineHeight: 33,
        marginLeft: 35,
    },
    phoneLabelBlack: {
        color: BLACK,
        fontFamily: "montserrat",
        fontSize: 23,
        fontStyle: "normal",
        fontWeight: "600",
        letterSpacing: -0.43,
        lineHeight: 33,
    },
    phoneLabelBlackLb: {
        color: BLACK,
        fontSize: 20,
        fontWeight: "800",
    },

    phoneLabelBlackSmallValue: {
        color: BLACK,
        fontFamily: "montserrat",
        fontSize: 20,
        fontWeight: "300",
    },
    phoneLabelBlackValue: {
        color: BLACK,
        fontFamily: "montserrat",
        fontSize: 23,
        fontWeight: "800",
        marginLeft: 3,
    },
    phoneView: {
        alignItems: "center",
        flexDirection: "row",
        height: 60,
        marginLeft: 35,
        marginRight: 35,
        marginTop: 30,
        width: "100%",
    },
    phoneViewReference: {
        alignItems: "center",
        flexDirection: "row",
        height: 60,
        marginLeft: 35,
        marginTop: 15,
        width: "100%",
    },
    phoneViewReference11: {
        alignItems: "center",
        flexDirection: "row",
        height: 50,
        marginLeft: 50,
        marginTop: 15,
        width: "100%",
    },
    phoneViewTransfer: {
        alignItems: "center",
        flexDirection: "row",
        height: 25,
        marginLeft: 35,
        marginRight: 35,
        marginTop: 18,
        width: "80%",
    },
    phoneViewTransferDummy: {
        alignItems: "center",
        flexDirection: "row",
    },
    referenceLabel: {
        color: DESC_COLOR,
        fontSize: 13,
        fontWeight: "500",
    },
    referenceModeViewCenter: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 15,
    },
    referenceText: {
        color: BLACK,
        fontSize: 15,
        fontWeight: "bold",
    },
    referenceView: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 1,
        marginLeft: 5,
        height: 35,
        width: "100%",
        flex: 1,
    },
    referenceViewCenter1: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 25,
    },

    referenceViewCenter2: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 10,
    },
    referenceViewCenter3: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 15,
    },
    rejectToButtonView: {
        marginLeft: 40,
        marginTop: -20,
    },
    rtpSubContainer: { marginTop: -17 },
    s2uAmountItem: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "column",
        justifyContent: FLEX_START,
        marginBottom: 0,
        marginLeft: 0,
        marginTop: 16,
    },

    s2uTitleItem: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "column",
        justifyContent: FLEX_START,
        marginBottom: 0,
        marginLeft: 0,
        marginTop: 24,
    },
    secure2uAmountLabel: {
        color: PRIMARY_YELLO,
        fontFamily: "montserrat",
        fontSize: 23,
        fontWeight: "bold",
        marginLeft: 55,
        marginTop: 8,
    },
    secure2uFirstRowView: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 28,
        marginLeft: 5,
        height: 30,
        width: "100%",
        flex: 1,
    },
    secure2uIcon: {
        height: 64,
        marginLeft: 0,
        marginTop: 60,
        width: 36,
    },
    secure2uLabel: {
        color: WHITE,
        fontFamily: "montserrat",
        fontSize: 23,
        fontWeight: "normal",
        marginLeft: 55,
        marginTop: 27,
    },
    secure2uRowView: {
        flex: 2.8,
        flexDirection: "column",
        height: 55,
        justifyContent: "center",
        marginRight: 60,
        marginTop: 35,
    },
    serviceTaxText: {
        color: DISABLED_DROPDOWN_TEXT,
        fontSize: 9,
        fontWeight: "normal",
    },
    statusCenter: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 8,
    },
    tagIcon: {
        height: 70,
        width: 56,
    },
    tagIconContainer1: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 60,
    },
    telcoNameText: {
        color: BLACK,
        fontSize: 13,
        fontStyle: "normal",
        fontWeight: "normal",
        letterSpacing: 0,
        lineHeight: 19,
    },
    textBelowDate: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 15,
    },
    textItemWrap: {
        flex: 1,
        flexWrap: "wrap",
        flexShrink: 1,
    },
    timeTransferView: {
        flex: 3.2,
        flexDirection: "column",
        height: 55,
        justifyContent: "center",
        marginRight: 60,
        marginTop: 20,
    },
    titleContainer: {
        justifyContent: FLEX_START,
        marginLeft: 35,
        marginTop: 34,
    },
    titleContainer1: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "column",
        justifyContent: "center",
        marginTop: 35,
    },
    titleContainer11: {
        justifyContent: FLEX_START,
        marginLeft: 50,
        marginTop: 40,
    },
    titleContainer12: {
        justifyContent: FLEX_START,
        marginLeft: 50,
        marginRight: 50,
        marginTop: 40,
    },

    titleContainer2: {
        alignContent: "center",
        alignItems: "center",
        flexDirection: "column",
        justifyContent: "center",
        marginTop: 30,
    },
    titleContainer3: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "column",
        justifyContent: FLEX_START,
        marginLeft: 35,
        marginTop: 35,
    },
    titleContainerCenter: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 40,
    },
    titleContainerCenter1: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 4,
    },
    titleContainerCenter11: {
        flexDirection: "row",
        height: 1,
        justifyContent: "center",
        marginTop: 0,
    },
    titleContainerCenter2: {
        alignContent: "center",
        alignItems: "center",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        marginLeft: 50,
        marginRight: 50,
        marginTop: 0,
        textAlign: "center",
    },
    titleContainerCenter3: {
        flexDirection: "row",
        flex: 0.5,
        justifyContent: "center",
        marginTop: 10,
    },
    titleContainerCenter33: {
        flexDirection: "row",
        flex: 0.1,
        height: 1,
        justifyContent: "center",
        marginTop: 0,
    },
    titleContainerCenterAck1: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 20,
    },
    titleContainerCenterDesc: {
        flexDirection: "row",
        justifyContent: "center",
        marginLeft: 55,
        marginRight: 55,
        marginTop: 40,
    },
    titleContainerCenterDesc2: {
        flexDirection: "column",
        justifyContent: "center",
        marginLeft: 55,
        marginRight: 55,
        marginTop: 20,
    },
    titleContainerCenterDesc3: {
        flexDirection: "column",
        justifyContent: "center",
        marginLeft: 55,
        marginRight: 55,
        marginTop: 10,
    },
    titleContainerCenterSecure2u: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 30,
    },
    titleContainerLeft1: {
        alignItems: FLEX_START,
        flexDirection: "row",
        justifyContent: FLEX_START,
        marginTop: 0,
    },
    titleContainerLeft11: {
        alignItems: FLEX_START,
        flexDirection: "row",
        height: 1,
        justifyContent: FLEX_START,
        marginTop: 0,
    },
    titleContainerOthers: {
        justifyContent: FLEX_START,
        marginLeft: 60,
    },
    titleContainerOthers1: {
        justifyContent: FLEX_START,
        marginLeft: 60,
    },
    titleContainerSend: {
        justifyContent: FLEX_START,
        marginLeft: 12,
    },
    titleContainerTransfer: {
        justifyContent: FLEX_START,
        marginLeft: 35,
        marginTop: 34,
    },
    titleContainerTransferNew: {
        justifyContent: FLEX_START,
        marginLeft: 1,
        width: "100%",
    },

    titleContainerTransferNew1: {
        justifyContent: FLEX_START,
        marginLeft: 3,
        paddingLeft: 2,
        width: "100%",
    },

    titleContainerTransferNewSmall: {
        justifyContent: FLEX_START,
        marginTop: -15,
    },

    titleText: {
        color: BLACK,
        fontSize: 18,
        fontStyle: "normal",
        fontWeight: "600",
        letterSpacing: 0,
        lineHeight: 19,
    },
    titleText1: {
        color: BLACK,
        fontSize: 20,
        fontWeight: "300",
    },
    titleText2: {
        alignContent: "center",
        alignItems: "center",
        alignSelf: "center",
        color: BLACK,
        fontSize: 23,
        fontWeight: "normal",
        textAlign: "center",
    },
    titleText2ErrorMsg: {
        alignContent: "center",
        alignItems: "center",
        alignSelf: "center",
        color: RED,
        fontSize: 11,
        fontWeight: "normal",
        marginTop: 15,
        textAlign: "center",
    },
    titleText3: {
        color: BLACK,
        fontSize: 13,
        fontWeight: "normal",
    },
    titleText4: {
        alignContent: "center",
        alignItems: "center",
        alignSelf: "center",
        color: BLACK,
        fontSize: 15,
        fontWeight: "bold",
        lineHeight: 35,
        marginLeft: 55,
        marginRight: 55,
        textAlign: "center",
    },
    titleText4Device: {
        color: BLACK,
        fontSize: 23,
        fontWeight: "normal",
        lineHeight: 33,
    },
    titleText4N: {
        color: BLACK,
        fontSize: 15,
        fontWeight: "600",
    },
    titleTextConfirmation: {
        color: DESC_COLOR,
        fontSize: 17,
        fontWeight: "900",
        textAlign: "center",
    },
    titleTextName: {
        alignContent: "center",
        alignItems: "center",
        alignSelf: "center",
        color: BLACK,
        fontSize: 20,
        fontWeight: "300",
        marginLeft: 55,
        marginRight: 55,
        textAlign: "center",
    },
    titleTextNew: {
        color: DESC_COLOR,
        fontSize: 17,
        fontWeight: "bold",
    },
    titleTextNew1: {
        alignContent: "center",
        alignItems: "center",
        alignSelf: "center",
        color: DESC_COLOR,
        fontSize: 23,
        fontWeight: "normal",
        marginLeft: 55,
        marginRight: 55,
        textAlign: "center",
    },
    toggleView: {
        alignItems: "flex-end",
        height: "100%",
        width: (167 * width) / 375,
    },
    toggleView1: {
        alignItems: "flex-end",
        height: "100%",
        width: (147 * width) / 375,
    },
    touchContainer: {
        flex: 1,
        justifyContent: "flex-end",
        marginRight: 10,
        marginTop: 40,
    },
    tranTypeLabel: {
        color: GREY,
        flex: 1.8,
        fontFamily: "montserrat",
        fontSize: 13,
        fontWeight: "normal",
        marginLeft: 50,
    },
    tranTypeValueLabel: {
        color: WHITE,
        flex: 1,
        fontFamily: "montserrat",
        fontSize: 13,
        fontWeight: "bold",
        marginRight: 0,
        textAlign: "right",
    },
    transferTypeViewCenter1: {
        flexDirection: "column",
        justifyContent: "center",
        marginTop: 10,
    },

    viewAcknowledgeImage: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "column",
        justifyContent: FLEX_START,
        marginBottom: 0,
        marginLeft: 0,
        marginTop: 126,
    },

    viewAcknowledgeImageSmall: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "column",
        justifyContent: FLEX_START,
        marginBottom: 0,
        marginLeft: 0,
        marginTop: 0,
    },

    viewAcknowledgeImageView: {
        alignContent: "center",
        alignItems: "center",
        backgroundColor: TRANSPARENT,
        borderRadius: 56 / 2,
        flexDirection: "row",
        height: 56,
        justifyContent: "center",
        width: 56,
    },
    viewRow: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "row",
        justifyContent: SPACE_BETWEEN,
        marginBottom: 17,
        marginLeft: 0,
        width: "100%",
    },
    viewRow2: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "row",
        justifyContent: SPACE_BETWEEN,
        marginBottom: 24,
        marginLeft: 0,
        width: "100%",
    },
    viewRow3: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "row",
        justifyContent: SPACE_BETWEEN,
        marginBottom: 10,
        marginLeft: 0,
        marginTop: 10,
        width: "100%",
    },
    viewRowDescriberItem: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "column",
        justifyContent: FLEX_START,
        marginBottom: 20,
        marginLeft: 0,
        marginTop: 20,
    },

    viewRowDescriberItemAck: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "column",
        justifyContent: FLEX_START,
        marginBottom: 21,
        marginLeft: 0,
        marginTop: 24,
    },
    viewRowDescriberItemSmall: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "column",
        justifyContent: FLEX_START,
        marginBottom: 2,
        marginLeft: 0,
        marginTop: 1,
    },

    viewRowDescriberOne: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "column",
        justifyContent: FLEX_START,
        marginBottom: 0,
        marginLeft: 0,
        marginTop: 4,
    },
    viewRowDescriberOneInner: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "column",
        justifyContent: FLEX_START,
        marginBottom: 0,
        marginLeft: 15,
        marginTop: 0,
    },
    viewRowAccountDropdown: {
        flexDirection: "column",
        height: 48,
        marginBottom: 20,
        marginTop: 4,
        width: "100%",
    },
    viewRowDescriberThree: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "column",
        justifyContent: FLEX_START,
        marginBottom: 0,
        marginLeft: 0,
        marginTop: 10,
    },
    viewRowDescriberTwo: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "row",
        justifyContent: FLEX_START,
        marginBottom: 0,
        marginLeft: 0,
        marginTop: 4,
    },
    viewRowFirst: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "row",
        justifyContent: SPACE_BETWEEN,
        marginLeft: 0,
        marginTop: 37,
    },
    viewRowLeftItem: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "row",
        justifyContent: FLEX_START,
        marginLeft: 0,
        marginTop: 0,
    },
    viewRowRightItem: {
        alignContent: "flex-end",
        alignItems: "flex-end",
        flexDirection: "column",
        justifyContent: SPACE_BETWEEN,
        marginLeft: 5,
        marginTop: 0,
        maxHeight: 40,
        paddingLeft: 5,
    },
    wrap: {
        flexWrap: "wrap",
        maxWidth: "70%",
    },
    viewRowRightItemOption: {
        alignContent: "flex-end",
        alignItems: "flex-end",
        flexDirection: "column",
        justifyContent: "flex-end",
        marginLeft: 0,
        marginRight: 0,
        marginTop: 0,
        paddingLeft: 0,
    },
    textBox: {
        alignItems: "flex-end",
        color: ROYAL_BLUE,
        fontFamily: MONTSERRAT_BOLD,
        fontSize: 14,
        fontStyle: "normal",
        fontWeight: "normal",
        marginTop: -4,
        maxHeight: 28,
        minWidth: 90,
        padding: 0,
    },
    viewRowRightItemWrap: {
        alignContent: "flex-end",
        alignItems: "flex-end",
        flexDirection: "row",
        flex: 1,
        justifyContent: SPACE_BETWEEN,
        marginLeft: 5,
        marginTop: 0,
        paddingLeft: 5,
    },
    viewRowS2uFirst: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "row",
        justifyContent: SPACE_BETWEEN,
        marginBottom: 16,
        marginLeft: 0,
        marginTop: 40,
    },
    viewRowS2uLast: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "row",
        justifyContent: SPACE_BETWEEN,
        marginBottom: 50,
        marginLeft: 0,
    },
    lineConfirm2: {
        backgroundColor: SWITCH_GREY,
        flexDirection: "row",
        height: 1,
        marginBottom: 25,
        marginTop: 24,
    },
    viewRowTermsItem: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "column",
        justifyContent: FLEX_START,
        marginLeft: 0,
        marginTop: 8,
    },
    viewSendRow: {
        marginBottom: 5,
    },
    viewSendRowSmall: {
        marginBottom: 25,
    },
    statusPillMargin: {
        marginBottom: 15,
    },
    wrapperBlue: {
        flex: 1,
    },
    viewRowTermsItem1: {
        alignContent: FLEX_START,
        alignItems: FLEX_START,
        flexDirection: "column",
        fontFamily: "montserrat",
        justifyContent: FLEX_START,
        marginBottom: 15,
        marginTop: 8,
    },
    accList: { paddingTop: 0 },
    mVertical20: {
        marginVertical: 20,
    },
    mb20: {
        marginBottom: 20,
    },
    mt5: {
        marginTop: 5,
    },
    mt10: {
        marginTop: 10,
    },
    mt20: {
        marginTop: 20,
    },
    listItem: {
        paddingBottom: 14,
    },
    infoIcon: { height: 14, marginLeft: 5, width: 14 },
    cardChild: {
        alignItems: "center",
        flex: 1,
        flexDirection: "row",
        justifyContent: "center",
    },
    top22: { top: 22 },
    greyLine: {
        backgroundColor: SWITCH_GREY,
        flexDirection: "row",
        height: 1,
        marginBottom: 15,
    },
});
