export const FN_FUND_TRANSFER_OWN_ACCT = "FN00002";
export const FN_FUND_TRANSFER_MAYBANK_FAVOURITE = "FN00003";
export const FN_FUND_TRANSFER_MAYBANK_FAVOURITE_FIRST = "FN00004";
export const FN_FUND_TRANSFER_MAYBANK_OPEN = "FN00005";
export const FN_FUND_TRANSFER_OTHER_BANK_FAVOURITE = "FN00006";
export const FN_FUND_TRANSFER_OTHER_BANK_FAVOURITE_FIRST = "FN00007";
export const FN_FUND_TRANSFER_OTHER_BANK_OPEN = "FN00008";
export const FN_DUIT_MAYBANK_OPEN = "FN00009";
export const FN_DUIT_MAYBANK_FAVOURITE = "FN00010";
export const FN_DUIT_MAYBANK_FAVOURITE_FIRST = "FN00011";
export const FN_DUIT_OTHER_BANK_OPEN = "FN00012";
export const FN_DUIT_OTHER_BANK_FAVOURITE = "FN00013";
export const FN_DUIT_OTHER_BANK_FAVOURITE_FIRST = "FN00014";
export const FN_MOBILE_RELOAD = "FN00015";
export const FN_PAY_CARDS = "FN00016";
export const FN_PAY_BILLS = "FN00017"; //FN00017", FN00099";
export const FN_KLIA_TICKET = "FN00018";
export const FN_WETIX_TICKET = "FN00019";
export const FN_AIRPAZ_TICKET = "FN00020";
export const FN_CTB_TICKET = "FN00021";
export const FN_TICKET_PURCHASE = "FN00022";
export const FN_DUIT_RECURRING = "FN00024";
export const FN_TABUNG_FUNDING = "FN00025";
export const FN_TABUNG_WITHDRAW = "FN00026";
export const FN_TABUNG_REMOVE = "FN00027";
export const FN_AUTO_TOPUP = "FN00032";
export const FN_CARD_MGMT = "FN00123";
export const FN_APPLY_CARD = "FN00121";
export const FN_CARD_RPLMENT = "FN00122";
export const FN_UPDATE_PRCHS_LIMIT = "FN00169";
export const FN_ACTIVATE_UPIN = "FN00141";
export const FN_CVV = "FN00142";
export const SPLIT_BILL_PAY = "FN00028";
export const FN_ASNB_TRANSFER = "FN00030";
export const FN_CC_ACTIVATION = "FN00124";
export const FN_CC_SET_PIN = "FN00125";
export const FN_TABUNG_CREATION = "FN00120";
export const APPLY_PLSTP = "FN00139";
export const FN_BAKONG_TRANSFER = "FN00031";
export const FN_CREDIT_CARD_APPLICATION = "FN00191";

export const FN00143 = "FN00143";
export const FN_MYGROSER = "FN00144";
export const FN_CONTACTLESS_WITHDRAWAL = "FN00145";
export const FN_OVERSEAS_OPEN = "FN00147";
export const FN_OVERSEAS_FAV_FIRST_TIME = "FN00148";
export const FN_OVERSEAS_FAV = "FN00149";
export const FN_ASNB_CONSENT_LINK = "FN00162";
export const FN_FD_PLACEMENT = "FN00189";
export const FN_M2U_DELETE = "FN00150";
export const FN_AUTO_BILLING = "FN00170";
export const FN_AUTO_DEBIT = "FN00184";
export const FN_CHARGE_CUSTOMER = "FN00206";
export const FN_SWITCH_ACCOUNT = "FN00207";
export const FN_RTP_DUITNOW_REQUEST = "FN00205";
export const FN_M2U_DEACTIVATION = "FN00192";
// Start S2U V4
export const FN_QRPAY_REG = "FNMAE00001";
export const FN_QRPAY_LIMIT_CHANGE = "FNMAE00002";
export const FN_ATM_CASHOUT = "FNMAE00003";
export const FN_ASNB_ADD_FAV = "FNMAE00004";
export const FN_CHANGE_PASSWORD = "FNMAE00005";
export const FN_CHANGE_PHNO = "FNMAE00006";
export const FN_CHANGE_SQ = "FNMAE00008";
export const FN_CHANGE_PIN = "FNMAE00009";
export const FN_DN_SUSPEND = "FNMAE00010";
export const FN_DN_UPDATE = "FNMAE00012"; //SWITCHING & UPDATE
export const FN_DN_DEREGISTER = "FNMAE00013";
export const FN_DN_ACTIVATE = "FNMAE00014";
export const FN_DN_TRANSFER = "FNMAE00029";
export const FN_BLOCK_DEBIT_CARD = "FNMAE00045";
export const FN_BLOCK_CASA = "FNMAE00056";
export const FN_BLOCK_CREDIT_CARD = "FNMAE00057";
export const FN_DELETE_M2U = "FNMAE00034";
export const FN_VIEW_CARD_CVV = "FNMAE00048";
export const FN_ETHICAL_CARDS_APPLICATION = "FNMAE00042";
export const FN_VIEW_CARD_EXPIRY = "FNMAE00061";

export const FN_BALANCE_TRANSFER = "FNMAE00051";
export const FN_DUITNOW_RECURRING = "FNMAE00049";
export const FN_ENABLE_ESI = "FNMAE00054";
export const FN_ASB_MAIN_APPLICANT = "FNMAE00007";
export const FN_ASB_MAIN_APPLICANT_MULTITIER = "FNMAE00052";
export const FN_ASB_MAIN_APPLICANT_APPROVAL = "FNMAE00046";
export const FN_ASB_MAIN_APPLICANT_APPROVAL_MULTITIER = "FNMAE00053";
export const FN_ASB_GUARANTOR = "FNMAE00059";
export const FN_ASB_GUARANTOR_MULTITIER = "FNMAE00060";
export const FN_SUPP_CARD_MAE = "FNMAE00026";
export const FN_FUND_TRANSFER_ZESTI = "FNMAE00017";
export const FN_FUND_TRANSFER_M2U_PREMIUM = "FNMAE00018";
export const FN_EZYPAY_PLUS = "FNMAE00044";
export const FN_CREATE_GROUP_TABUNG = "FNMAE00055";
export const FN_JOIN_GROUP_TABUNG = "FNMAE00063";

// End S2U V4
export const FN_TABUNG_HAJI_MBB_OWN_TH = "FN00163";
export const FN_TABUNG_HAJI_MBB_OTH_TH = "FN00164";
export const FN_TABUNG_HAJI_TH_OWN_MBB = "FN00165";
export const FN_TABUNG_HAJI_TH_OTH_MBB = "FN00166";
export const FN_TABUNG_HAJI_TH_OWN_TH = "FN00167";
export const FN_TABUNG_HAJI_TH_OTH_TH = "FN00168";

export const THIRD_PARTY_FUND_TRANSFER = "THIRD_PARTY_FUND_TRANSFER";
export const IBFT_FUND_TRANSFER = "IBFT_FUND_TRANSFER";
export const GIRO_FUND_TRNSFER = "GIRO_FUND_TRNSFER";
export const SEC2U_REGISTRATION_REQ = "SEC2U_REGISTRATION_REQ";
export const SEC2U_REGISTRATION_VERIFY = "SEC2U_REGISTRATION_VERIFY";
export const MOBILE_RELOAD_OTP = "MOBILE_RELOAD_OTP";
export const DUITNOW_RECURRING_TRANSFER_OTP = "DUITNOW_RECURRING_TRANSFER_OTP";
export const DUITNOW_CREDIT_TRANSFER_OTP = "DUITNOW_CREDIT_TRANSFER_OTP";
export const BILL_PAYMENT_OTP = "BILL_PAYMENT_OTP";
export const JOMPAY_OTP = "JOMPAY_OTP";
export const GOAL_FUND = "GOAL_FUND";
export const GOAL_WITHDRAW = "GOAL_WITHDRAW";
export const GOAL_REMOVE = "GOAL_REMOVE";
export const DUITNOW_FIRST_TIME_REQ = "DUITNOW_FIRST_TIME_REQ";
export const SEND_RCV_MONEY = "SEND_RCV_MONEY";
export const SPLIT_BILL_TRANSFER = "SPLIT_BILL";

export const MBB_BANK_CODE_MAYBANK = "0000";
export const MBB_BANK_SWIFT_CODE = "MBBEMYKL";
export const MBB_BANK_AQUIRER_ID = "000000";
export const MBB_BANK_CODE = "MAYBANK";

export const FUND_TRANSFER_TYPE_OWN_ACCT = "OWN_ACCT";
export const FUND_TRANSFER_TYPE_MAYBANK = "MAYBANK";
export const FUND_TRANSFER_TYPE_INTERBANK = "INTERBANK";
export const FUND_TRANSFER_TYPE_DUITNOW_ON_US = "DUITNOW_ON_US";
export const FUND_TRANSFER_TYPE_DUITNOW_OFF_US = "DUITNOW_OFF_US";
export const FUND_TRANSFER_TYPE_QUICK = "QUICK";

export const SUB_TYPE_OPEN = "OPEN";
export const SUB_TYPE_FAVORITE_FIRST_TIME = "FAVORITE_FIRST_TIME";
export const SUB_TYPE_FAVORITE = "FAVORITE";

export const TWO_FA_TYPE_SECURE2U_PUSH = "SECURE2U_PUSH";
export const TWO_FA_TYPE_SECURE2U_PULL = "SECURE2U_PULL";
export const TWO_FA_TYPE_TAC = "TAC";
export const TWO_FA_TYPE_S2U = "S2U";
export const TWO_FA_TYPE_NONE = "NONE";

export const fundingCode = {
    // Own Maybank Account Fund transfer
    1: FN_FUND_TRANSFER_OWN_ACCT,

    // Favourite Maybank Account Fund transfer
    2: FN_FUND_TRANSFER_MAYBANK_FAVOURITE,

    // Open Maybank Account Fund transfer
    3: FN_FUND_TRANSFER_MAYBANK_OPEN,
    15: FN_FUND_TRANSFER_MAYBANK_OPEN,

    // Open Other Bank Open Fund transfer
    4: FN_FUND_TRANSFER_OTHER_BANK_OPEN,

    // Open Other Bank Favorite Fund Transfer
    5: FN_FUND_TRANSFER_OTHER_BANK_FAVOURITE,

    // Favourite First Time Maybank Account Fund transfer 6
    6: FN_FUND_TRANSFER_MAYBANK_FAVOURITE_FIRST,

    // Open Other Bank Favorite First Fund Transfer 7
    7: FN_FUND_TRANSFER_OTHER_BANK_FAVOURITE_FIRST,

    //RELOAD
    11: FN_MOBILE_RELOAD,

    // Duit Now Maybank Open
    12: FN_DUIT_MAYBANK_OPEN,

    //Pay Cards
    13: FN_PAY_CARDS,
    14: "",
    16: "",

    //Pay Bills
    17: FN_PAY_BILLS,

    // Tabung Funding
    18: FN_TABUNG_FUNDING,

    // Tabung Withdraw
    19: FN_TABUNG_WITHDRAW,

    // Tabung Remove
    20: FN_TABUNG_REMOVE,

    // Wetix
    21: FN_WETIX_TICKET,

    // AirPaz
    22: FN_AIRPAZ_TICKET,

    // KLIA
    23: FN_KLIA_TICKET,

    // Catch that bus
    24: FN_CTB_TICKET,

    //Duit Now Maybank Favourite 25
    25: FN_DUIT_MAYBANK_FAVOURITE,

    //Duit Now Maybank Favourite First 26
    26: FN_DUIT_MAYBANK_FAVOURITE_FIRST,

    //Duit Now Other Bank  Open 27
    27: FN_DUIT_OTHER_BANK_OPEN,
    28: FN_DUIT_OTHER_BANK_FAVOURITE,
    29: FN_DUIT_OTHER_BANK_FAVOURITE_FIRST,
    30: FN_DUIT_RECURRING,
    31: SPLIT_BILL_PAY,
    32: FN_ASNB_TRANSFER,
    33: FN_TABUNG_CREATION,
    34: FN_CC_SET_PIN,
    35: FN_CC_ACTIVATION,
    36: FN_CARD_MGMT,
    37: FN_APPLY_CARD,
    38: FN_CARD_RPLMENT,
    39: FN_AUTO_TOPUP,
    40: FN_BAKONG_TRANSFER,
    41: FN_ACTIVATE_UPIN,
    42: FN_CVV,
    43: APPLY_PLSTP,
    44: FN00143,
    45: FN_MYGROSER,
    46: FN_CONTACTLESS_WITHDRAWAL,
    47: FN_M2U_DELETE,
    48: FN_ASNB_CONSENT_LINK,
    49: FN_OVERSEAS_FAV_FIRST_TIME,
    50: FN_OVERSEAS_FAV,
    51: FN_OVERSEAS_OPEN,
    52: FN_FD_PLACEMENT,
    53: FN_UPDATE_PRCHS_LIMIT,
    54: FN_CREDIT_CARD_APPLICATION,
    55: FN_M2U_DEACTIVATION,
    65: FN_QRPAY_REG,

    //Tabung Haji Transfer Open 56-61
    56: FN_TABUNG_HAJI_MBB_OWN_TH,
    57: FN_TABUNG_HAJI_MBB_OTH_TH,
    58: FN_TABUNG_HAJI_TH_OWN_MBB,
    59: FN_TABUNG_HAJI_TH_OTH_MBB,
    60: FN_TABUNG_HAJI_TH_OWN_TH,
    61: FN_TABUNG_HAJI_TH_OTH_TH,

    //DuitNow Auto Billing
    70: FN_AUTO_BILLING,
    71: FN_AUTO_DEBIT,
    72: FN_CHARGE_CUSTOMER,
    73: FN_SWITCH_ACCOUNT,

    //RTP DuitNow Request
    74: FN_RTP_DUITNOW_REQUEST,
};
export const FN_ZAKAT_REGISTER = "FNMAE00030";
export const FN_ZAKAT_ACCOUNT = "FNMAE00031";
export const FN_ZAKAT_MOBILE = "FNMAE00032";
export const FN_ZAKAT_BODY = "FNMAE00033";
export const FN_ZAKAT_CANCEL = "FNMAE00035";
