export const MYKAD_CODE = "01";
export const PASSPORT_CODE = "05";
export const GENDER_MALE_CODE = "M";
export const GENDER_FEMALE_CODE = "F";
export const MAE_INDICATOR_CONVENTIONAL = "0Y";
export const MAE_INDICATOR_ISLAMIC = "CC";
export const HIGH_RISK_CUSTOMER_CODE = "HR";
export const MEDIUM_RISK_CUSTOMER_CODE = "MR";
export const LOW_RISK_CUSTOMER_CODE = "LR";
export const PRE_QUAL_PRE_LOGIN_FLAG = "prelogin";
export const PRE_QUAL_POST_LOGIN_FLAG = "postlogin";
export const ZEST_CASA_CLEAR_ALL = "CLEAR_ALL";
export const CARD_STP = "CARD_STP";
export const CARD_STP_VERIFY = "CARD_STP_VERIFY";
export const OTP_VERIFY = "TAC Application";
export const ZESTI_STP = "ZESTI_STP";
export const ZESTI_STP_VERIFY = "ZESTI_STP_VERIFY";
export const MYKAD_ID_TYPE = "MyKad";
export const PASSPORT_ID_TYPE = "Passport";
export const MAY_ONLY_CUST = "MAE1";
export const CHECK_08_SCREEN = "CHECK_08_SCREEN";

// User status
export const ZEST_NTB_USER = "ZEST_NTB_USER";
export const ZEST_DRAFT_USER = "ZEST_DRAFT_USER";
export const ZEST_DRAFT_BRANCH_USER = "ZEST_DRAFT_BRANCH_USER";
export const ZEST_M2U_ONLY_USER = "ZEST_M2U_ONLY_USER";
export const ZEST_FULL_ETB_USER = "ZEST_FULL_ETB_USER";
export const ZEST_NON_KYC_USER = "ZEST_NON_KYC_USER";
export const ZEST_UNIDENTIFIED_USER = "ZEST_UNIDENTIFIED_USER";
export const ZEST_HIGH_RISK_USER = "ZEST_HIGH_RISK_USER";
export const ZEST_MAE_ONLY_USER = "ZEST_MAE_ONLY_USER";
export const ZEST_DEBIT_CARD_USER = "ZEST_DEBIT_CARD_USER";
export const ZEST_DEBIT_CARD_NTB_USER = "ZEST_DEBIT_CARD_NTB_USER";
export const ZEST_DEBIT_CARD_ACTIVATE_ACCOUNT_USER = "ZEST_DEBIT_CARD_ACTIVATE_ACCOUNT_USER";

// Custom exception codes
export const FUNDS_TRANSFER_EXCEPTION = 444;
export const M2U_SCREEN_SCORE_EXCEPTION = 4994;
export const CREATE_ACCOUNT_SCREEN_PARTY_TIMEOUT = 104;
export const CREATE_ACCOUNT_SCORE_PARTY_TIMEOUT = 105;
export const PREQUAL_PENDING_ACCOUNT_CREATION_STATUS = "3300";
export const CREATE_ACCOUNT_TIMEOUT_EXCEPTION = 5500;
export const CREATE_ACCOUNT_FAILURE_EXCEPTION = 103;
export const CREATE_ACCOUNT_SCREEN_CREATE_PARTY_TIMEOUT = "101";
export const CREATE_ACCOUNT_SCREEN_CREATE_ACCOUNT_FAILURE = "802";
