export const ASB_GUARANTOR_PREPOSTQUAL_LOADING = () => ({});

export const ASB_GUARANTOR_PREPOSTQUAL_ERROR = (error) => ({
    error,
});

export const ASB_GUARANTOR_PREPOSTQUAL_SUCCESS = (
    data,
    statusCode,
    statusDesc,
    pan,
    isStaff,
    addr1,
    addr2,
    addr3,
    addr4,
    birthDate,
    bodInd,
    branchApprovalStatusCode,
    city,
    custStatus,
    customerName,
    customerRiskRating,
    deChequeHostStatus,
    emailAddress,
    empType,
    empTypeValue,
    employerName,
    finanicalObjective,
    gcif,
    genderCode,
    genderValue,
    idNo,
    idType,
    localCifNo,
    m2uAccessNo,
    m2uIndicator,
    maeInd,
    mobileNo,
    monthlyIncomeRange,
    monthlyIncomeRangeValue,
    nationality,
    occupationCode,
    occupationValue,
    onBoardingStatusInfo,
    onboardingIndicatorCode,
    onlineRegUrl,
    pep,
    postCode,
    preferredBRDistrict,
    preferredBRState,
    preferredBranch,
    purpose,
    purposeValue,
    raceCode,
    raceValue,
    resumeStageInd,
    rsaIndicator,
    saDailyInd,
    saFormInvestmentExp,
    saFormInvestmentNature,
    saFormInvestmentRisk,
    saFormInvestmentTerm,
    saFormPIDM,
    saFormProductFeature,
    saFormSecurities,
    saFormSuitability,
    saTermInd,
    screeningStatus,
    sector,
    sectorValue,
    staffInd,
    state,
    stateValue,
    stateCode,
    universalCifNo,
    title,
    sourceOfFund,
    sourceOfFundValue,
    viewPartyResult,
    requestMsgRefNo,
    mainStpReferenceNo,

    country,
    countryCode,
    mobCountryCode,
    mobAreaCode,
    religionCode,
    religionValue,
    employmentTypeCode,
    employmentTypeValue,
    occupationSectorCode,
    occupationSectorValue,
    nameOfEmployer,
    salutationCode,
    salutationValue,
    dateOfBirth,
    addressType,
    grossIncome,
    stpreferenceNo,
    lastUpdatedDate,
    unitHolderId,
    idTypeCode,
    maritalStatus,
    mainApplicantName
) => ({
    data,
    statusCode,
    statusDesc,
    pan,
    isStaff,
    addr1,
    addr2,
    addr3,
    addr4,
    birthDate,
    bodInd,
    branchApprovalStatusCode,
    city,
    custStatus,
    customerName,
    customerRiskRating,
    deChequeHostStatus,
    emailAddress,
    empType,
    empTypeValue,
    employerName,
    finanicalObjective,
    gcif,
    genderCode,
    genderValue,
    idNo,
    idType,
    localCifNo,
    m2uAccessNo,
    m2uIndicator,
    maeInd,
    mobileNo,
    monthlyIncomeRange,
    monthlyIncomeRangeValue,
    nationality,
    occupationCode,
    occupationValue,
    onBoardingStatusInfo,
    onboardingIndicatorCode,
    onlineRegUrl,
    pep,
    postCode,
    preferredBRDistrict,
    preferredBRState,
    preferredBranch,
    purpose,
    purposeValue,
    raceCode,
    raceValue,
    resumeStageInd,
    rsaIndicator,
    saDailyInd,
    saFormInvestmentExp,
    saFormInvestmentNature,
    saFormInvestmentRisk,
    saFormInvestmentTerm,
    saFormPIDM,
    saFormProductFeature,
    saFormSecurities,
    saFormSuitability,
    saTermInd,
    screeningStatus,
    sector,
    sectorValue,
    staffInd,
    state,
    stateValue,
    stateCode,
    universalCifNo,
    title,
    sourceOfFund,
    sourceOfFundValue,
    viewPartyResult,
    requestMsgRefNo,
    mainStpReferenceNo,

    country,
    countryCode,
    mobCountryCode,
    mobAreaCode,
    religionCode,
    religionValue,
    employmentTypeCode,
    employmentTypeValue,
    occupationSectorCode,
    occupationSectorValue,
    nameOfEmployer,
    salutationCode,
    salutationValue,
    dateOfBirth,
    addressType,
    grossIncome,
    stpreferenceNo,
    lastUpdatedDate,
    unitHolderId,
    idTypeCode,
    maritalStatus,
    mainApplicantName,
});

export const ASB_GUARANTOR_PREPOSTQUAL_ID_NO_UPDATE = (
    idNo,
    mainApplicantName,
    stpReferenceNo
) => ({
    idNo,
    mainApplicantName,
    stpReferenceNo,
});

export const ASB_UPDATE_PREPOSTQUAL_DETAILS = (
    resultAsbApplicationDetails,
    resumeData,
    loanInformation,
    eligibilityData,
    stpEligibilityResponse,
    stpScreenResume,
    stpReferenceNo,
    stpAssessmentId,
    stpDeclarePdpa,
    idNo,
    lastUpdatedDate,
    eligibilityCheckOutcomeData,
    additionalDetails
) => ({
    resultAsbApplicationDetails,
    resumeData,
    loanInformation,
    eligibilityData,
    stpEligibilityResponse,
    stpScreenResume,
    stpReferenceNo,
    stpAssessmentId,
    stpDeclarePdpa,
    idNo,
    lastUpdatedDate,
    eligibilityCheckOutcomeData,
    additionalDetails,
});

export const ASB_UPDATE_OVERALL_VALIDATION_DETAILS = (overallValidationResult) => ({
    overallValidationResult,
});

export const ASB_UPDATE_FINANCING_DETAILS = (financingDetailsList) => ({ financingDetailsList });

export const ASB_UPDATE_PERSONAL_DETAILS = (personDetailsList) => ({ personDetailsList });

export const ASB_UPDATE_EMPLOYMENT_DETAILS = (employmentDetailList) => ({ employmentDetailList });

export const ASB_UPDATE_PREPOSTQUAL_DETAILS_FEAILED = (error) => ({ error });

export const ASB_PREPOSTQUAL_SCORE_PARTY_SUCCESS = (
    responseJsonString,
    customerRiskRatingCode,
    customerRiskRatingValue,
    manualRiskRatingCode,
    manualRiskRatingValue,
    assessmentId
) => ({
    responseJsonString,
    customerRiskRatingCode,
    customerRiskRatingValue,
    manualRiskRatingCode,
    manualRiskRatingValue,
    assessmentId,
});
export const ASB_PREPOSTQUAL_SCORE_PARTY_FAILURE = (scorePartyError) => ({ scorePartyError });

export const ASB_GUARANTOR_PREPOSTQUAL_CLEAR = () => ({});
