import { StyleSheet } from 'react-native';
import { Dimensions, Image } from 'react-native';
const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
    mainNormalView: {
        width: 333 * width/375,        
        height: 106 * height/667,
        borderRadius: 43 * height/667,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: '#dfdfdf',
        backgroundColor: 'white',
    },
    mainElevatedView: {
        width: 333 * width/375,        
        height: 106 * height/667,
        borderRadius: 43 * height/667,
        borderWidth: StyleSheet.hairlineWidth,
        elevation: 2,
        borderColor: '#dfdfdf',
        backgroundColor: 'white',
    },
    mainLeaderboardView: {
        width: 333 * width/375,        
        height: 90 * height/667,
        borderRadius: 45 * height/667,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: '#dfdfdf',
        backgroundColor: 'white',
    },
    rankingView: {
        position: 'absolute',
        width: 20 * width/375,
        height: 20 * width/375,
        marginTop: 33 * height/667,
        marginLeft: 25 * width/375,
        borderRadius: 10 * width/375,
        elevation: 2,
        backgroundColor: '#ffde00',      
        alignItems: 'center',
        justifyContent: 'center',
    },    
    rankingText: {
        fontFamily: "Montserrat-SemiBold",
        // fontWeight: '600',
        fontSize: 11,
        color: 'black',
    },
    profilePicView: {
        position: 'absolute',
        width: 44 * width/375,
        height: 44 * width/375,
        marginTop: 21 * height/667,
        marginLeft: 35 * width/375,
        borderRadius: 22 * width/375,
        // borderWidth: 2,
        // borderColor: 'white',
        // elevation: 3,
        // backgroundColor: 'red',      
        alignItems: 'center',
        justifyContent: 'center',
    },
    profilePicImage: {
        // position: 'absolute',
        width: 39 * width/375,
        height: 39 * width/375,
        borderRadius: 19.5 * width/375,
    },
    nameView: {
        position: 'absolute',
        width: 120 * width/375,
        marginTop: 33 * height/667,
        marginLeft: 89 * width/375, 
        justifyContent: 'center',
    },
    nameTextIsUser: {
        fontFamily: "Montserrat-SemiBold",
        // fontWeight: '600',
        fontSize: 15,
        color: '#4a90e2',
    },
    nameTextNotUser: {
        fontFamily: "Montserrat-SemiBold",
        // fontWeight: '600',
        fontSize: 15,
        color: 'black',
    },
    stepsView: {
        position: 'absolute',
        width: 75 * width/375,
        height: 19 * height/667,
        marginTop: 33 * height/667,
        marginLeft: 239 * width/375,
        // backgroundColor: '#ffde00',      
        alignItems: 'center',
        justifyContent: 'center',
    },
    stepsText: {
        fontFamily: "Montserrat-Regular",
        // fontWeight: '400',
        fontSize: 15,
        color: 'black',
    },
    pendingText: {
        fontFamily: "Montserrat-Regular",
        // fontWeight: '400',
        fontStyle: 'italic',
        fontSize: 15,
        color: 'black',
    },
    statusView: {
        position: 'absolute',
        height: 18 * height/667,
        marginTop: 73 * height/667,
        marginLeft: 34 * width/375,
        opacity: 0.3,    
        alignItems: 'center',
        justifyContent: 'center',
    },
    statusText: {
        fontFamily: "Montserrat-Regular",
        // fontWeight: '400',
        fontSize: 11,
        color: 'black',
    },
}
)
