export const productDetailsSample = {
    message: "success",
    code: 200,
    challenge: null,
    result: {
        code: 200,
        status: "QR000",
        text: "success",
        message: null,
        productDetail: {
            merchantId: "MBUAT1205503",
            products: [
                {
                    productId: "MKPRD1001104",
                    name: "not suit bike",
                    imagePaths: [
                        "https://test.vts.maybank.com.my:8553/api/v1/mobile/Images/MKPRD1001104.jpeg",
                    ],
                    logo: "https://test.vts.maybank.com.my:8553/api/v1/mobile/Images/MKPRD1001104.jpeg",
                    priceAmount: 5.3,
                    currency: "RM",
                    suitableBike: true,
                    sku: "0",
                    shortDesc: "not suit bike",
                    longDesc: "",
                    size: "0.01cm x 0.11cm x 0.01cm",
                    weight: 1,
                    categoryName: null,
                    updateDate: null,
                    deliveryServiceCode: null,
                    outletAddress: null,
                    merchantContactNo: null,
                    outOfCoverage: null,
                    image: null,
                    netAmtWithoutDeliveryAmt: null,
                    orderDetailId: null,
                    totalAmt: null,
                    quantity: null,
                    totalWeight: null,
                    productDeepLinkUrl:
                        "Hey, I'd like to share with you not suit bike from digi 07 mdel I found on Sama-Sama Lokal. Check them out and lend a helping hand to our locals!\n\n https://test.vts.maybank.com.my:8553/api/v1/mobile/ssl/mae/MBUAT1205503/digi07mdel/MKPRD1001104",
                    avail: true,
                    optionCategoryId: 158,
                    displayOrder: 0,
                    isSst: false,
                    afterSstTotalAmt: null,
                    optionGroup: [
                        {
                            optionGroupId: "7873",
                            name: "Flavour",
                            display_order: "",
                            isRequired: 1,
                            minSelection: "1",
                            maxSelection: "1",
                            active: 1,
                            options: [
                                {
                                    optionId: "19062",
                                    name: "lime",
                                    displayOrder: "1",
                                    amount: "2.00",
                                    sstAmount: "",
                                    active: 1,
                                },
                                {
                                    optionId: "19061",
                                    name: "durian",
                                    displayOrder: "2",
                                    amount: "1.00",
                                    sstAmount: "",
                                    active: 1,
                                },
                                {
                                    optionId: "12219",
                                    name: "orange",
                                    displayOrder: "3",
                                    amount: "2.00",
                                    sstAmount: "",
                                    active: 1,
                                },
                                {
                                    optionId: "12222",
                                    name: "strawberry",
                                    displayOrder: "4",
                                    amount: "0.00",
                                    sstAmount: "",
                                    active: 1,
                                },
                                {
                                    optionId: "12221",
                                    name: "chocolate",
                                    displayOrder: "5",
                                    amount: "0.00",
                                    sstAmount: "",
                                    active: 1,
                                },
                            ],
                        },
                    ],
                },
            ],
        },
    },
};
