name: MAE-DCAPPS-Build
env:
    DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
    #FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    ANDROID_HOME: /etc/github/Android/sdk
    ## Fixing the self-sign cert issues on this GitHub Server. (NA for Maybanks-MacBook-1)
    NODE_EXTRA_CA_CERTS: /etc/github/githubcert.pem
    Fastlane_generate_git_tag_semVer: "0.9.12"
    buildNumber: ${{github.run_number}}

on:
    workflow_dispatch:
    # push:
    #  branches: [ master ]
    # pull_request:
    #  branches: [ master ]

jobs:
    Android_CIND_build:
        runs-on: [MACBOOK1]
        environment:
            name: dcapps
        # needs: [ IOS_build ]
        steps:
            - uses: actions/checkout@v3
            - name: set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: "11"
                  distribution: "adopt"
                  #cache: gradle

            #- name: Copy Local.properties
            #run: cp /Users/maybankidh1/MAYA-FASTFILE/Android/local.properties .
            - name: Grant execute permission for gradlew
              run: chmod +x android/gradlew
            - name: Build with Gradle
              run: |

                  rm package-lock.json && rm Gemfile.lock
                  npm i --legacy-peer-deps
                  bundle install
                  fastlane android cind
    Android_NTT_build:
        runs-on: [MACBOOK1]
        needs: [Android_CIND_build]
        steps:
            - uses: actions/checkout@v3
            - name: set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: "11"
                  distribution: "adopt"
                  #cache: gradle

            #- name: Copy Local.properties
            #run: cp /Users/maybankidh1/MAYA-FASTFILE/Android/local.properties .

            - name: Grant execute permission for gradlew
              run: chmod +x android/gradlew
            - name: Build with Gradle
              run: |

                  rm package-lock.json && rm Gemfile.lock
                  npm i --legacy-peer-deps
                  bundle install
                  fastlane android ntt
    Android_kldc_build:
        runs-on: [MACBOOK1]
        needs: [Android_NTT_build]
        steps:
            - uses: actions/checkout@v3
            - name: set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: "11"
                  distribution: "adopt"
                  #cache: gradle

            #- name: Copy Local.properties
            #run: cp /Users/maybankidh1/MAYA-FASTFILE/Android/local.properties .

            - name: Grant execute permission for gradlew
              run: chmod +x android/gradlew
            - name: Build with Gradle
              run: |

                  rm package-lock.json && rm Gemfile.lock
                  npm i --legacy-peer-deps
                  bundle install
                  fastlane android kldc
