name: MAE-Mobile-Sonarqube scan
env:
    DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
    #FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    ANDROID_HOME: /etc/github/Android/sdk
    ## Fixing the self-sign cert issues on this GitHub Server. (NA for Maybanks-MacBook-1)
    NODE_EXTRA_CA_CERTS: /etc/github/githubcert.pem
    Fastlane_generate_git_tag_semVer: "0.9.12"
    buildNumber: ${{github.run_number}}

on:
    # workflow_dispatch:
    # push:
    #  branches: [ master ]
    pull_request:
    #  branches: [ master ]
    # schedule:
    #     - cron: "* 16 * * *"

jobs:
    cron_job:
        # scheduled:
        runs-on: [MACBOOK1]
        #needs: [ IOS_build ]
        steps:
            #         - uses: actions/checkout@v3
            #         - name: set up JDK 11
            #           uses: actions/setup-java@v2
            #           with:
            #               java-version: "11"
            #               distribution: "adopt"
            #               #cache: gradle

            #         #- name: Copy Local.properties
            #         #run: cp /Users/maybankidh1/MAYA-FASTFILE/Android/local.properties .

            #         - name: Grant execute permission for gradlew
            #           run: chmod +x android/gradlew

            - name: sonarqube scan
              run: /etc/github/sonar-scanner-macosx/bin/sonar-scanner -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=maya-mobile -Dsonar.projectName=maya-mobile  -Dsonar.sourceEncoding=UTF-8 -Dsonar.java.binaries=. -Dsonar.sonar.skipPackageDesign=true -Dsonar.projectVersion=${{ github.run_number }}
